{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.742.0 (23.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"HaloITSM-AuthURL\",\"HaloITSM-ResourceURL\",\"HaloITSM-Tenant\",\"HaloITSM-ClientID\",\"HaloITSM-Secret\",\"GenerateHaloToken\",\"FetchedHaloToken\",\"FetchPage\",\"GenerateByPage\",\"FetchPages\",\"Items\",\"TicketTypes\",\"Users\",\"Statuses Raw\",\"Clients\",\"Sites\",\"Suppliers\",\"Tickets\",\"TicketsRaw\",\"Agents Raw\",\"Agents\",\"Agent teams\",\"Teams\",\"StatusMapping\",\"Statuses\",\"MeasuresTable\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "HaloITSM-ClientID",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"YOUR-API-ClientID\" meta [IsParameterQuery=true, List={\"YOUR-API-ClientID\"}, DefaultValue=\"YOUR-API-ClientID\", Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "9a8b46bb-abab-4e94-8630-8655c6314bcc",
        "queryGroup": "00 Utilities\\00-00 Params"
      },
      {
        "name": "HaloITSM-AuthURL",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"https://YOUR-DOMAIN.nethelpdesk.com/auth\" meta [IsParameterQuery=true, List={\"https://YOUR-DOMAIN.nethelpdesk.com/auth\"}, DefaultValue=\"https://YOUR-DOMAIN.nethelpdesk.com/auth\", Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d5d10281-e432-486e-9d44-36084f58be4b",
        "queryGroup": "00 Utilities\\00-00 Params"
      },
      {
        "name": "HaloITSM-ResourceURL",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"https://YOUR-DOMAIN.nethelpdesk.com/api\" meta [IsParameterQuery=true, List={\"https://YOUR-DOMAIN.nethelpdesk.com/api\"}, DefaultValue=\"https://YOUR-DOMAIN.nethelpdesk.com/api\", Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "320ac076-ad7d-4b8b-852b-d41830b5bece",
        "queryGroup": "00 Utilities\\00-00 Params"
      },
      {
        "name": "HaloITSM-Secret",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"YOUR-API-SECRET\" meta [IsParameterQuery=true, List={\"YOUR-API-SECRET\"}, DefaultValue=\"YOUR-API-SECRET\", Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "8260996e-c064-43e9-a1c1-fa04b8fff976",
        "queryGroup": "00 Utilities\\00-00 Params"
      },
      {
        "name": "HaloITSM-Tenant",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"YOUR-DOMAIN\" meta [IsParameterQuery=true, List={\"YOUR-DOMAIN\"}, DefaultValue=\"YOUR-DOMAIN\", Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d88db245-5a78-4f88-af54-9c4bf4dfe5e7",
        "queryGroup": "00 Utilities\\00-00 Params"
      },
      {
        "name": "GenerateHaloToken",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
          "        loginURL = #\"HaloITSM-AuthURL\",",
          "        TokenUri = \"/token\", // which domain is this a token for",
          "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
          "        TokenResponse = Json.Document(",
          "            Web.Contents(loginURL",
          "\t\t\t    , [RelativePath = TokenUri",
          "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
          "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
          "\t\t\t    ]",
          "            ) // end web contents",
          "        ), // end json",
          "        generatedToken = TokenResponse[access_token] // assign token value",
          "    in",
          "    generatedToken",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "3c5d662f-cd05-44d8-a1d2-286e1bd31a0f",
        "queryGroup": "00 Utilities\\00-01 Auth Function"
      },
      {
        "name": "FetchedHaloToken",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": [
          "let",
          "    Source = GenerateHaloToken(#\"HaloITSM-AuthURL\", #\"HaloITSM-ClientID\", #\"HaloITSM-Secret\")",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "d7c7d7b9-11bf-4a57-a9b8-7902ba851c0c",
        "queryGroup": "00 Utilities\\00-01 Auth Function"
      },
      {
        "name": "Items",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Record"
          }
        ],
        "expression": [
          "let",
          "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
          "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
          "        loginURL = #\"HaloITSM-AuthURL\",",
          "        TokenUri = \"/token\", // which domain is this a token for",
          "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
          "        TokenResponse = Json.Document(",
          "            Web.Contents(loginURL",
          "\t\t\t    , [RelativePath = TokenUri",
          "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
          "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
          "\t\t\t    ]",
          "            ) // end web contents",
          "        ), // end json",
          "        generatedToken = TokenResponse[access_token] // assign token value",
          "    in",
          "    generatedToken,",
          "    myToken = makeToken(",
          "                        #\"HaloITSM-ResourceURL\"",
          "                        , #\"HaloITSM-ClientID\"",
          "                        , #\"HaloITSM-Secret\"",
          "                    ) // end makeToken",
          "    , ",
          "    // Ping API for json",
          "    Source = Json.Document(",
          "        Web.Contents(",
          "            #\"HaloITSM-ResourceURL\"",
          "            , [",
          "                RelativePath = \"Item\"",
          "                , Headers = [",
          "                    Authorization = \"Bearer \" ",
          "                    &  myToken",
          "                ]",
          "            ]",
          "        )",
          "    )",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "c9dc9909-52c6-4945-8456-54b20de396ad",
        "queryGroup": "01 API returns\\01-01 Paginated"
      },
      {
        "name": "FetchPage",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "// TicketsRaw",
          "let ",
          "    FetchPage = (url as text, page_size as number, skipRows as number) as table =>",
          "let",
          "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
          "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
          "        loginURL = #\"HaloITSM-AuthURL\",",
          "        TokenUri = \"/token\", // which domain is this a token for",
          "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
          "        TokenResponse = Json.Document(",
          "            Web.Contents(loginURL",
          "\t\t\t    , [RelativePath = TokenUri",
          "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
          "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
          "\t\t\t    ]",
          "            ) // end web contents",
          "        ), // end json",
          "        generatedToken = TokenResponse[access_token] // assign token value",
          "    in",
          "    generatedToken,",
          "    myToken = makeToken(",
          "                        #\"HaloITSM-ResourceURL\"",
          "                        , #\"HaloITSM-ClientID\"",
          "                        , #\"HaloITSM-Secret\"",
          "                    ) // end makeToken",
          "    , ",
          "    // Ping API for json",
          "    contents = Web.Contents(",
          "            #\"HaloITSM-ResourceURL\"",
          "            , [",
          "                RelativePath = \"Tickets\"",
          "                , Headers = [",
          "                    Authorization = \"Bearer \" &  myToken",
          "                    , viewid = \"1\"",
          "                    , paginated = \"TRUE\"",
          "                ]",
          "                , Query = [",
          "                    maxResults= Text.From(page_size)",
          "                    , startAt = Text.From(skipRows)]",
          "            ]",
          "    )",
          "    , json = Json.Document(contents)",
          "    , Value = json[tickets]",
          "    , table = Table.FromList(Value, Splitter.SplitByNothing(), null, null, ExtraValues.Error)",
          "    in",
          "        table meta [skipRows = skipRows + page_size, total = 100]",
          "",
          "in",
          "    FetchPage"
        ],
        "kind": "m",
        "lineageTag": "9a57d23f-32d9-4d47-bf69-18689727ace5",
        "queryGroup": "99 Testing\\Functions"
      },
      {
        "name": "GenerateByPage",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "//Query Name: GenerateByPage",
          "let",
          "    Source = (getNextPage as function, optional tableType as type) as table =>",
          "    let",
          "        listOfPages = List.Generate(",
          "            () => getNextPage(null),",
          "            (lastPage) => lastPage <> null,",
          "            (lastPage) => getNextPage(lastPage)",
          "            ),",
          "        tableOfPages = Table.FromList(listOfPages, Splitter.SplitByNothing(), {\"Column1\"}),",
          "        firstRow = tableOfPages{0}?,",
          "        keys = if tableType = null then Table.ColumnNames(firstRow[Column1])",
          "               else Record.FieldNames(Type.RecordFields(Type.TableRow(tableType))),",
          "        appliedType = if tableType = null then Value.Type(firstRow[Column1]) else tableType",
          "    in",
          "        if tableType = null and firstRow = null then",
          "            Table.FromRows({})",
          "        else",
          "        Value.ReplaceType(Table.ExpandTableColumn(tableOfPages, \"Column1\", keys), appliedType)",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "d7fbb0e8-e770-4959-8133-1aa2f75d43a9",
        "queryGroup": "99 Testing\\Functions"
      },
      {
        "name": "FetchPages",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    FetchPages = (url as text, pageSize as number) => ",
          "let ",
          "    Source = GenerateByPage(",
          "    (previous) =>",
          "    let",
          "        skipRows = if previous = null then 0 else Value.Metadata(previous)[skipRows],",
          "        totalItems = if previous = null then 0 else Value.Metadata(previous)[total],",
          "        table = if previous = null or Table.RowCount(previous) = pageSize then ",
          "                    FetchPage(url, pageSize, skipRows) ",
          "\t\telse null",
          "    in table,",
          "    ",
          "    type table [Column1])",
          "in",
          "    Source",
          "in",
          "    FetchPages"
        ],
        "kind": "m",
        "lineageTag": "dccc49b6-90c8-44b8-a2d2-b07d5fb84245",
        "queryGroup": "99 Testing\\Functions"
      },
      {
        "name": "TicketsRaw",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "List"
          }
        ],
        "expression": [
          "let",
          "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
          "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
          "        loginURL = #\"HaloITSM-AuthURL\",",
          "        TokenUri = \"/token\", // which domain is this a token for",
          "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
          "        TokenResponse = Json.Document(",
          "            Web.Contents(loginURL",
          "\t\t\t    , [RelativePath = TokenUri",
          "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
          "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
          "\t\t\t    ]",
          "            ) // end web contents",
          "        ), // end json",
          "        generatedToken = TokenResponse[access_token] // assign token value",
          "    in",
          "    generatedToken,",
          "    myToken = makeToken(",
          "                        #\"HaloITSM-ResourceURL\"",
          "                        , #\"HaloITSM-ClientID\"",
          "                        , #\"HaloITSM-Secret\"",
          "                    ) // end makeToken",
          "    , ",
          "    // Ping API for json",
          "    Source = Json.Document(",
          "        Web.Contents(",
          "            #\"HaloITSM-ResourceURL\"",
          "            , [",
          "                RelativePath = \"Tickets\"",
          "                , Headers = [",
          "                    Authorization = \"Bearer \" &  myToken",
          "                    , viewid = \"1\"",
          "                    , paginated = \"TRUE\"",
          "                ]",
          "            ]",
          "        )",
          "    )[tickets]",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "c4b1370a-2132-450c-bf81-eaad04d69638",
        "queryGroup": "01 API returns\\01-01 Paginated"
      },
      {
        "name": "Agents Raw",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
          "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
          "        loginURL = #\"HaloITSM-AuthURL\",",
          "        TokenUri = \"/token\", // which domain is this a token for",
          "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
          "        TokenResponse = Json.Document(",
          "            Web.Contents(loginURL",
          "\t\t\t    , [RelativePath = TokenUri",
          "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
          "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
          "\t\t\t    ]",
          "            ) // end web contents",
          "        ), // end json",
          "        generatedToken = TokenResponse[access_token] // assign token value",
          "    in",
          "    generatedToken,",
          "    myToken = makeToken(",
          "                        #\"HaloITSM-ResourceURL\"",
          "                        , #\"HaloITSM-ClientID\"",
          "                        , #\"HaloITSM-Secret\"",
          "                    ) // end makeToken",
          "    , ",
          "    // Ping API for json",
          "    Source = Json.Document(",
          "        Web.Contents(",
          "            #\"HaloITSM-ResourceURL\"",
          "            , [",
          "                RelativePath = \"Agent\"",
          "                , Headers = [",
          "                    Authorization = \"Bearer \" ",
          "                    &  myToken",
          "                ]",
          "            ]",
          "        )",
          "    ),",
          "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "    #\"Expanded Column1\" = Table.ExpandRecordColumn(",
          "        #\"Converted to Table\", \"Column1\", {",
          "            \"id\", \"name\", \"team\", \"isdisabled\", \"initials\", \"firstname\", \"surname\", \"colour\", \"jobtitle\", \"sms\", \"extensionnumber\", \"is_agent\", \"teams\", \"departments\", \"linemanager\", \"exchange_authorized\", \"sentinel_authorized\", \"licence_type\", \"use\", \"allowbeyondtrustinvites\", \"namewithinactive\", \"apptsync\", \"enableshifts\", \"sendemailerrors\", \"can_approve_purchaseorder\", \"can_approve_quote\", \"email\", \"lastlogindate\", \"isapiagent\"",
          "        }",
          "        , {",
          "            \"id\", \"name\", \"team\", \"isdisabled\", \"initials\", \"firstname\", \"surname\", \"colour\", \"jobtitle\", \"sms\", \"extensionnumber\", \"is_agent\", \"teams\", \"departments\", \"linemanager\", \"exchange_authorized\", \"sentinel_authorized\", \"licence_type\", \"use\", \"allowbeyondtrustinvites\", \"namewithinactive\", \"apptsync\", \"enableshifts\", \"sendemailerrors\", \"can_approve_purchaseorder\", \"can_approve_quote\", \"email\", \"lastlogindate\", \"isapiagent\"",
          "        }",
          "    ),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Column1\",{{\"id\", \"agent id\"}}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"\",null,Replacer.ReplaceValue,{\"agent id\", \"name\", \"team\", \"isdisabled\", \"initials\", \"firstname\", \"surname\", \"colour\", \"jobtitle\", \"sms\", \"extensionnumber\", \"is_agent\", \"teams\", \"departments\", \"linemanager\", \"exchange_authorized\", \"sentinel_authorized\", \"licence_type\", \"use\", \"allowbeyondtrustinvites\", \"namewithinactive\", \"apptsync\", \"enableshifts\", \"sendemailerrors\", \"can_approve_purchaseorder\", \"can_approve_quote\", \"email\", \"lastlogindate\", \"isapiagent\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"isdisabled\", type logical}, {\"exchange_authorized\", type logical}, {\"sentinel_authorized\", type logical}, {\"enableshifts\", type logical}, {\"sendemailerrors\", type logical}, {\"can_approve_purchaseorder\", type logical}, {\"can_approve_quote\", type logical}, {\"isapiagent\", type logical}, {\"lastlogindate\", type datetimezone}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "0e616127-781e-438e-a1d9-b34ca25220d5",
        "queryGroup": "01 API returns\\01-00 SingleQuery"
      },
      {
        "name": "StatusMapping",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"lZLBC4IwGMX/FdnZg5su3dHSKIiKMjqIBzGrgWwHjf79nKvQGH16+gbvx/be3pemCCMbJdKKZDuX4eYY9yZGmZ0i0p7O671BJ1oPvkByOBl0Bug+aMEFCa89hc+cN1zcrPmD16KsawPtdjQFHKnIcV3kVd6UF8MtnsbUo1vZ8Cs3UrSj8GySNexPw9XnR1KUPeWdiQWacEECahirBhe5KMqqGiT93MM0RsGXPLBI7EzKT+iwg58+dQUE3h8GWSeqxt3dWsnK1DXz9aI6o37KxeMw8tdV9gI=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"status id\" = _t, Category = _t, External = _t, Terminal = _t, Order = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"status id\", Int64.Type}, {\"Category\", type text}, {\"External\", type logical}, {\"Terminal\", type logical}, {\"Order\", Int64.Type}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "e6ddeac8-04dc-4e30-8539-925a440e6cc7",
        "queryGroup": "02 Staging tables"
      },
      {
        "name": "Statuses Raw",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
          "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
          "        loginURL = #\"HaloITSM-AuthURL\",",
          "        TokenUri = \"/token\", // which domain is this a token for",
          "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
          "        TokenResponse = Json.Document(",
          "            Web.Contents(loginURL",
          "\t\t\t    , [RelativePath = TokenUri",
          "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
          "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
          "\t\t\t    ]",
          "            ) // end web contents",
          "        ), // end json",
          "        generatedToken = TokenResponse[access_token] // assign token value",
          "    in",
          "    generatedToken,",
          "    myToken = makeToken(",
          "                        #\"HaloITSM-ResourceURL\"",
          "                        , #\"HaloITSM-ClientID\"",
          "                        , #\"HaloITSM-Secret\"",
          "                    ) // end makeToken",
          "    , ",
          "    // Ping API for json",
          "    Source = Json.Document(",
          "        Web.Contents(",
          "            #\"HaloITSM-ResourceURL\"",
          "            , [",
          "                RelativePath = \"Status\"",
          "                , Headers = [",
          "                    Authorization = \"Bearer \" ",
          "                    &  myToken",
          "                ]",
          "            ]",
          "        )",
          "    ),",
          "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"guid\", \"name\", \"shortname\", \"type\", \"sequence\", \"colour\", \"slaaction\", \"showonquickchange\", \"timeuntilloffhold\", \"statuschangeto\", \"statuschangetofreq\", \"useworkinghours\", \"statusemailfreqdays\", \"statusemailid\", \"statusnochangehours\", \"nochangehoursrecurring\", \"statusnochangehoursmanager\", \"statusnochangehoursmanagerrecurring\", \"statusnochangehourssection\", \"statusnochangehourssectionrecurring\", \"nochangetemplate\"}, {\"id\", \"guid\", \"name\", \"shortname\", \"type\", \"sequence\", \"colour\", \"slaaction\", \"showonquickchange\", \"timeuntilloffhold\", \"statuschangeto\", \"statuschangetofreq\", \"useworkinghours\", \"statusemailfreqdays\", \"statusemailid\", \"statusnochangehours\", \"nochangehoursrecurring\", \"statusnochangehoursmanager\", \"statusnochangehoursmanagerrecurring\", \"statusnochangehourssection\", \"statusnochangehourssectionrecurring\", \"nochangetemplate\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Column1\",{{\"showonquickchange\", type logical}, {\"statusnochangehourssectionrecurring\", type logical}, {\"statusnochangehoursmanagerrecurring\", type logical}, {\"nochangehoursrecurring\", type logical}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"id\", \"status id\"}}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed Columns\",{\"status id\", \"guid\", \"name\", \"shortname\", \"statusemailid\", \"nochangehoursrecurring\"})",
          "in",
          "    #\"Removed Other Columns\""
        ],
        "kind": "m",
        "lineageTag": "77586c1f-7605-41ba-a91c-7888c20c5c7c",
        "queryGroup": "01 API returns\\01-00 SingleQuery"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "00 Utilities"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "00 Utilities\\00-00 Params"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "00 Utilities\\00-01 Auth Function"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "01 API returns"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "02 Staging tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ],
        "folder": "03 Report Tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "6"
          }
        ],
        "folder": "99 Testing"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "01 API returns\\01-00 SingleQuery"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "01 API returns\\01-01 Paginated"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "99 Testing\\Functions"
      }
    ],
    "relationships": [
      {
        "name": "3894d2d1-006d-4f7b-9727-b6cc019a0375",
        "fromColumn": "tickettype_id",
        "fromTable": "Tickets",
        "toColumn": "ticket type id",
        "toTable": "TicketTypes"
      },
      {
        "name": "fcb24200-3c2e-438a-ad77-99afa77b1f87",
        "fromColumn": "user_id",
        "fromTable": "Tickets",
        "toColumn": "user id",
        "toTable": "Users"
      },
      {
        "name": "70e4bc1f-62c0-42cc-9833-c0d6357b459e",
        "fromColumn": "client_id",
        "fromTable": "Users",
        "toColumn": "client id",
        "toTable": "Clients"
      },
      {
        "name": "a8116590-0e0e-41c9-b6ed-bd885faa26d5",
        "fromColumn": "client_id",
        "fromTable": "Sites",
        "toColumn": "client id",
        "toTable": "Clients"
      },
      {
        "name": "5531123c-d30e-4367-aa6b-ace28699166d",
        "fromColumn": "agent_id",
        "fromTable": "Tickets",
        "toColumn": "agent id",
        "toTable": "Agents"
      },
      {
        "name": "861ab5ea-13c5-4110-994b-6f44244faf26",
        "fromColumn": "agent id",
        "fromTable": "Agent teams",
        "toColumn": "agent id",
        "toTable": "Agents"
      },
      {
        "name": "7b61e748-a971-4f4e-864c-8c9d77fac6ec",
        "fromColumn": "team_id",
        "fromTable": "Agent teams",
        "toColumn": "team_id",
        "toTable": "Teams"
      },
      {
        "name": "1e7c6081-ffd2-43e6-8e1d-93196de0f1ac",
        "fromColumn": "status_id",
        "fromTable": "Tickets",
        "toColumn": "status id",
        "toTable": "Statuses"
      }
    ],
    "sourceQueryCulture": "en-AU",
    "tables": [
      {
        "name": "TicketTypes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ticket type id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aff29af9-9cb9-407b-904b-1db32b162410",
            "sourceColumn": "ticket type id",
            "summarizeBy": "none"
          },
          {
            "name": "guid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21ded55f-7768-40f0-8ae7-8cb9eda9f11c",
            "sourceColumn": "guid",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "320cf3c5-443e-4239-9c52-1f024bd57705",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "sequence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65aeb886-f189-4b35-a790-6fb39db66d5e",
            "sourceColumn": "sequence",
            "summarizeBy": "none"
          },
          {
            "name": "default_sla",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd997279-e3ed-4859-b8c7-8c114639d053",
            "sourceColumn": "default_sla",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a6c0e50-0f52-4cd7-ab27-190c2f955326",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dee2ada6-4740-4dd3-b599-04f33043a3ba",
            "sourceColumn": "group_name",
            "summarizeBy": "none"
          },
          {
            "name": "jira_issue_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3acd66d8-9966-4620-983b-045776052ce7",
            "sourceColumn": "jira_issue_type",
            "summarizeBy": "none"
          },
          {
            "name": "cancreate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "258c3493-e541-4399-a01e-2b3216cdd99f",
            "sourceColumn": "cancreate",
            "summarizeBy": "none"
          },
          {
            "name": "agentscanselect",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "9744ffbe-bb5d-488f-bb58-6fab49f35e64",
            "sourceColumn": "agentscanselect",
            "summarizeBy": "none"
          },
          {
            "name": "itilrequesttype",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dca0278-e16c-4fac-b373-6b19370cf4b5",
            "sourceColumn": "itilrequesttype",
            "summarizeBy": "none"
          },
          {
            "name": "allowattachments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3c468f4e-4541-4535-b252-80059f48defa",
            "sourceColumn": "allowattachments",
            "summarizeBy": "none"
          },
          {
            "name": "copyattachmentstochild",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f835fc48-ae71-4d18-a9bd-6e689a1f3911",
            "sourceColumn": "copyattachmentstochild",
            "summarizeBy": "none"
          },
          {
            "name": "is_sprint",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "9658b439-86de-47c7-8a12-2a77dd9e227d",
            "sourceColumn": "is_sprint",
            "summarizeBy": "none"
          },
          {
            "name": "enduserscanselect",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "389dad1b-a084-4ea5-b80d-d19096445887",
            "sourceColumn": "enduserscanselect",
            "summarizeBy": "none"
          },
          {
            "name": "anonymouscanselect",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "e54f6669-dbe8-4b26-8983-09c8f75ab7d4",
            "sourceColumn": "anonymouscanselect",
            "summarizeBy": "none"
          },
          {
            "name": "kanbanstatuschoice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5bc3277-f2ba-42a1-997b-7e67d2436061",
            "sourceColumn": "kanbanstatuschoice",
            "summarizeBy": "none"
          },
          {
            "name": "kanbanstatuschoice_list",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66e1f5da-ead1-4374-bbf5-e43ed2fbd3f5",
            "sourceColumn": "kanbanstatuschoice_list",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cc849e06-7c92-4a41-ba3b-764008565686",
        "partitions": [
          {
            "name": "TicketTypes",
            "mode": "import",
            "queryGroup": "01 API returns\\01-00 SingleQuery",
            "source": {
              "expression": [
                "let",
                "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
                "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
                "        loginURL = #\"HaloITSM-AuthURL\",",
                "        TokenUri = \"/token\", // which domain is this a token for",
                "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
                "        TokenResponse = Json.Document(",
                "            Web.Contents(loginURL",
                "\t\t\t    , [RelativePath = TokenUri",
                "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
                "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
                "\t\t\t    ]",
                "            ) // end web contents",
                "        ), // end json",
                "        generatedToken = TokenResponse[access_token] // assign token value",
                "    in",
                "    generatedToken,",
                "    myToken = makeToken(",
                "                        #\"HaloITSM-ResourceURL\"",
                "                        , #\"HaloITSM-ClientID\"",
                "                        , #\"HaloITSM-Secret\"",
                "                    ) // end makeToken",
                "    , ",
                "    // Ping API for json",
                "    Source = Json.Document(",
                "        Web.Contents(",
                "            #\"HaloITSM-ResourceURL\"",
                "            , [",
                "                RelativePath = \"TicketType\"",
                "                , Headers = [",
                "                    Authorization = \"Bearer \" ",
                "                    &  myToken",
                "                ]",
                "            ]",
                "        )",
                "    ),",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"guid\", \"name\", \"sequence\", \"default_sla\", \"group_id\", \"group_name\", \"jira_issue_type\", \"cancreate\", \"agentscanselect\", \"itilrequesttype\", \"allowattachments\", \"copyattachmentstochild\", \"is_sprint\", \"enduserscanselect\", \"anonymouscanselect\", \"kanbanstatuschoice\", \"kanbanstatuschoice_list\"}, {\"id\", \"guid\", \"name\", \"sequence\", \"default_sla\", \"group_id\", \"group_name\", \"jira_issue_type\", \"cancreate\", \"agentscanselect\", \"itilrequesttype\", \"allowattachments\", \"copyattachmentstochild\", \"is_sprint\", \"enduserscanselect\", \"anonymouscanselect\", \"kanbanstatuschoice\", \"kanbanstatuschoice_list\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Column1\",{{\"cancreate\", type logical}, {\"agentscanselect\", type logical}, {\"allowattachments\", type logical}, {\"copyattachmentstochild\", type logical}, {\"is_sprint\", type logical}, {\"enduserscanselect\", type logical}, {\"anonymouscanselect\", type logical}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"id\", \"ticket type id\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Users",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "user id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce1edcff-440c-4787-8fb8-14b4488b40ac",
            "sourceColumn": "user id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48ef134e-ed65-49db-80d1-9403cef92325",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "site_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ebf491a-3efb-4771-906f-4a2a5348edf5",
            "sourceColumn": "site_id",
            "summarizeBy": "none"
          },
          {
            "name": "site_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b8dd80d-9b8a-4ec5-9688-595fe9347f5d",
            "sourceColumn": "site_name",
            "summarizeBy": "none"
          },
          {
            "name": "client_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b619119f-22e8-4f0e-91c0-2e86746620e8",
            "sourceColumn": "client_name",
            "summarizeBy": "none"
          },
          {
            "name": "firstname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f9f2a72-e1fa-43f2-8f7a-ede5093f2053",
            "sourceColumn": "firstname",
            "summarizeBy": "none"
          },
          {
            "name": "surname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6b8ee96-a25d-43d6-a049-43e559aead14",
            "sourceColumn": "surname",
            "summarizeBy": "none"
          },
          {
            "name": "initials",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d72ab68e-ddbb-42c0-997a-7ac892b70d90",
            "sourceColumn": "initials",
            "summarizeBy": "none"
          },
          {
            "name": "emailaddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea756dd5-fc57-417d-b680-cd98b9fbebb4",
            "sourceColumn": "emailaddress",
            "summarizeBy": "none"
          },
          {
            "name": "phonenumber_preferred",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9dd18a3-7d6e-4976-9872-52694842cd23",
            "sourceColumn": "phonenumber_preferred",
            "summarizeBy": "none"
          },
          {
            "name": "sitephonenumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fff54bc7-dbaa-4e93-ade3-3b9c681c10ef",
            "sourceColumn": "sitephonenumber",
            "summarizeBy": "none"
          },
          {
            "name": "phonenumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbb410d3-d854-4739-a295-b4040a4ee230",
            "sourceColumn": "phonenumber",
            "summarizeBy": "none"
          },
          {
            "name": "telpref",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a743852-4bef-4df9-92a8-6cfb4903e4fe",
            "sourceColumn": "telpref",
            "summarizeBy": "none"
          },
          {
            "name": "activedirectory_dn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f73affd0-00e1-4f8d-a484-75d723e733b9",
            "sourceColumn": "activedirectory_dn",
            "summarizeBy": "none"
          },
          {
            "name": "login",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5a64c3e-cf74-4a41-a9ea-06c3ff610d83",
            "sourceColumn": "login",
            "summarizeBy": "none"
          },
          {
            "name": "inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "cf79d8e3-d260-4ab4-87fe-28fd9819ecf7",
            "sourceColumn": "inactive",
            "summarizeBy": "none"
          },
          {
            "name": "colour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c9fb753-6df1-4eee-935d-a737ad7e3c93",
            "sourceColumn": "colour",
            "summarizeBy": "none"
          },
          {
            "name": "isimportantcontact",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "20b59b83-64fd-488d-af8b-e4f840e5d121",
            "sourceColumn": "isimportantcontact",
            "summarizeBy": "none"
          },
          {
            "name": "other1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be6d2d5f-4d11-4640-8abc-5740f30507f7",
            "sourceColumn": "other1",
            "summarizeBy": "none"
          },
          {
            "name": "other2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97345932-facf-45f3-9492-bc20ce171c91",
            "sourceColumn": "other2",
            "summarizeBy": "none"
          },
          {
            "name": "neversendemails",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "90edad83-f155-4212-8402-901eed84eed6",
            "sourceColumn": "neversendemails",
            "summarizeBy": "none"
          },
          {
            "name": "priority_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8a564b4-f2af-455c-bcf2-1f1b1fd18b7b",
            "sourceColumn": "priority_id",
            "summarizeBy": "none"
          },
          {
            "name": "linked_agent_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7bfabb06-d320-48a0-b449-7cfd013506b7",
            "sourceColumn": "linked_agent_id",
            "summarizeBy": "none"
          },
          {
            "name": "isserviceaccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "79a6466c-ba18-45eb-a6f7-edbb79c0ce5f",
            "sourceColumn": "isserviceaccount",
            "summarizeBy": "none"
          },
          {
            "name": "isimportantcontact2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c588db47-8d10-408c-9b71-ca99fa6d2048",
            "sourceColumn": "isimportantcontact2",
            "summarizeBy": "none"
          },
          {
            "name": "connectwiseid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ced6f4f2-e2d4-40a9-af63-ffc7abd06c3a",
            "sourceColumn": "connectwiseid",
            "summarizeBy": "none"
          },
          {
            "name": "autotaskid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfdb31a9-595e-46c2-9e2a-0c105ad548a7",
            "sourceColumn": "autotaskid",
            "summarizeBy": "none"
          },
          {
            "name": "messagegroup_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7336b425-3905-4128-a731-a2ab7ab3a8f7",
            "sourceColumn": "messagegroup_id",
            "summarizeBy": "none"
          },
          {
            "name": "use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "16a609b0-a5e9-46b2-968e-de14e39d5107",
            "sourceColumn": "use",
            "summarizeBy": "none"
          },
          {
            "name": "client_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23a39e0b-1a22-40ca-8d3e-492ada809f9e",
            "sourceColumn": "client_id",
            "summarizeBy": "none"
          }
        ],
        "description": "may need pagination",
        "lineageTag": "fb7d9636-1131-4678-a273-60bf93e39487",
        "partitions": [
          {
            "name": "Users",
            "mode": "import",
            "queryGroup": "01 API returns\\01-01 Paginated",
            "source": {
              "expression": [
                "let",
                "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
                "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
                "        loginURL = #\"HaloITSM-AuthURL\",",
                "        TokenUri = \"/token\", // which domain is this a token for",
                "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
                "        TokenResponse = Json.Document(",
                "            Web.Contents(loginURL",
                "\t\t\t    , [RelativePath = TokenUri",
                "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
                "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
                "\t\t\t    ]",
                "            ) // end web contents",
                "        ), // end json",
                "        generatedToken = TokenResponse[access_token] // assign token value",
                "    in",
                "    generatedToken,",
                "    myToken = makeToken(",
                "                        #\"HaloITSM-ResourceURL\"",
                "                        , #\"HaloITSM-ClientID\"",
                "                        , #\"HaloITSM-Secret\"",
                "                    ) // end makeToken",
                "    , ",
                "    // Ping API for json",
                "    Source = Json.Document(",
                "        Web.Contents(",
                "            #\"HaloITSM-ResourceURL\"",
                "            , [",
                "                RelativePath = \"Users\"",
                "                , Headers = [",
                "                    Authorization = \"Bearer \" ",
                "                    &  myToken",
                "                ]",
                "            ]",
                "        )",
                "    )[users],",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"name\", \"site_id\", \"site_name\", \"client_name\", \"firstname\", \"surname\", \"initials\", \"emailaddress\", \"phonenumber_preferred\", \"sitephonenumber\", \"phonenumber\", \"telpref\", \"activedirectory_dn\", \"login\", \"inactive\", \"colour\", \"isimportantcontact\", \"other1\", \"other2\", \"neversendemails\", \"priority_id\", \"linked_agent_id\", \"isserviceaccount\", \"isimportantcontact2\", \"connectwiseid\", \"autotaskid\", \"messagegroup_id\", \"use\", \"client_id\"}, {\"id\", \"name\", \"site_id\", \"site_name\", \"client_name\", \"firstname\", \"surname\", \"initials\", \"emailaddress\", \"phonenumber_preferred\", \"sitephonenumber\", \"phonenumber\", \"telpref\", \"activedirectory_dn\", \"login\", \"inactive\", \"colour\", \"isimportantcontact\", \"other1\", \"other2\", \"neversendemails\", \"priority_id\", \"linked_agent_id\", \"isserviceaccount\", \"isimportantcontact2\", \"connectwiseid\", \"autotaskid\", \"messagegroup_id\", \"use\", \"client_id\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Column1\",{{\"inactive\", type logical}, {\"isimportantcontact\", type logical}, {\"neversendemails\", type logical}, {\"isserviceaccount\", type logical}, {\"isimportantcontact2\", type logical}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"id\", \"user id\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Clients",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "client id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92d9f932-49b0-4b2f-92d5-9bbde53c7ceb",
            "sourceColumn": "client id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "968125ef-aa2b-4b41-b9cd-0b3fca243534",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "toplevel_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "534d6d4f-e374-43f2-ab1c-7a5cfa22f8bb",
            "sourceColumn": "toplevel_id",
            "summarizeBy": "none"
          },
          {
            "name": "toplevel_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6bfebec9-5244-40f5-be18-43c33e376442",
            "sourceColumn": "toplevel_name",
            "summarizeBy": "none"
          },
          {
            "name": "inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "24e0a5d9-bc91-481e-83d9-37949ae8a583",
            "sourceColumn": "inactive",
            "summarizeBy": "none"
          },
          {
            "name": "colour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f0c624b-658c-43f0-9392-44e8a2f7a46e",
            "sourceColumn": "colour",
            "summarizeBy": "none"
          },
          {
            "name": "confirmemail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4dada178-a17a-40d4-bacb-b7cb9b31860e",
            "sourceColumn": "confirmemail",
            "summarizeBy": "none"
          },
          {
            "name": "actionemail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c372eef-4928-4238-812c-69b59a0a6bcc",
            "sourceColumn": "actionemail",
            "summarizeBy": "none"
          },
          {
            "name": "clearemail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d2266c0-11cf-49c6-81cc-88a5bac95559",
            "sourceColumn": "clearemail",
            "summarizeBy": "none"
          },
          {
            "name": "messagegroup_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e023883-2c14-4ae1-a5e1-05bd1d2c3101",
            "sourceColumn": "messagegroup_id",
            "summarizeBy": "none"
          },
          {
            "name": "from_address_override",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b992959-35ac-402b-94b7-21ceea992ace",
            "sourceColumn": "from_address_override",
            "summarizeBy": "none"
          },
          {
            "name": "mailbox_override",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11a7c17d-aa05-481b-ade6-86d1e3f8f814",
            "sourceColumn": "mailbox_override",
            "summarizeBy": "none"
          },
          {
            "name": "default_mailbox_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17fe9b41-5f92-4233-ac5e-67b45963cae1",
            "sourceColumn": "default_mailbox_id",
            "summarizeBy": "none"
          },
          {
            "name": "item_tax_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f519ca8f-4b46-406c-ba33-048b9544fd43",
            "sourceColumn": "item_tax_code",
            "summarizeBy": "none"
          },
          {
            "name": "service_tax_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8c1e0ba-fe9e-4416-a51d-71b2ca18393a",
            "sourceColumn": "service_tax_code",
            "summarizeBy": "none"
          },
          {
            "name": "prepay_tax_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ded6eed-6ef5-46ae-a526-d887f4cba064",
            "sourceColumn": "prepay_tax_code",
            "summarizeBy": "none"
          },
          {
            "name": "contract_tax_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cea3cc56-fba6-4dfe-aa6f-51530dba0f02",
            "sourceColumn": "contract_tax_code",
            "summarizeBy": "none"
          },
          {
            "name": "pritech",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8a851c9-9363-4cbe-bd83-b49d846cf062",
            "sourceColumn": "pritech",
            "summarizeBy": "none"
          },
          {
            "name": "sectech",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f62696bd-5291-42c1-8a87-ace6bb918541",
            "sourceColumn": "sectech",
            "summarizeBy": "none"
          },
          {
            "name": "accountmanagertech",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f824329-dbb3-4c8b-9c0c-50f1be29f806",
            "sourceColumn": "accountmanagertech",
            "summarizeBy": "none"
          },
          {
            "name": "use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ec867eb-9ea5-48a5-a00f-cf93852a5f33",
            "sourceColumn": "use",
            "summarizeBy": "none"
          },
          {
            "name": "xero_tenant_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3037c4e-9738-4016-b7e9-488473d9f028",
            "sourceColumn": "xero_tenant_id",
            "summarizeBy": "none"
          },
          {
            "name": "overridepdftemplateinvoice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa789b27-8bbb-4275-aa18-d29e9ad486a0",
            "sourceColumn": "overridepdftemplateinvoice",
            "summarizeBy": "none"
          },
          {
            "name": "kashflow_tenant_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "421d2cc8-fefe-4d0f-a4b4-21b64cef89c9",
            "sourceColumn": "kashflow_tenant_id",
            "summarizeBy": "none"
          },
          {
            "name": "client_to_invoice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bff84639-0f3b-4bb0-8c61-2512d23116f3",
            "sourceColumn": "client_to_invoice",
            "summarizeBy": "none"
          },
          {
            "name": "invoiceduedaysextraclient",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d241e83-a244-4c84-b22d-d228c4da670b",
            "sourceColumn": "invoiceduedaysextraclient",
            "summarizeBy": "none"
          },
          {
            "name": "itglue_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f48ff53-8e07-4077-821d-bba716424107",
            "sourceColumn": "itglue_id",
            "summarizeBy": "none"
          },
          {
            "name": "clientcurrency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19ac6f5b-90ac-48c8-bb4e-1c480c4f22b8",
            "sourceColumn": "clientcurrency",
            "summarizeBy": "none"
          },
          {
            "name": "sentinel_subscription_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d0f9993-ed2d-4bcb-904e-c0c219163beb",
            "sourceColumn": "sentinel_subscription_id",
            "summarizeBy": "none"
          },
          {
            "name": "sentinel_workspace_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "302c5839-1453-44fe-95eb-00f15de7831b",
            "sourceColumn": "sentinel_workspace_name",
            "summarizeBy": "none"
          },
          {
            "name": "sentinel_resource_group_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3904045a-6be6-4413-ba40-06082d74a5f6",
            "sourceColumn": "sentinel_resource_group_name",
            "summarizeBy": "none"
          },
          {
            "name": "default_currency_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06c1081d-7de7-4a76-b084-853bf21503a3",
            "sourceColumn": "default_currency_code",
            "summarizeBy": "none"
          },
          {
            "name": "client_to_invoice_recurring",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a219cb7-2795-400c-9a08-4d082dd8da6d",
            "sourceColumn": "client_to_invoice_recurring",
            "summarizeBy": "none"
          },
          {
            "name": "dbc_company_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6055fa9c-589d-44c2-9b84-27a402ac939a",
            "sourceColumn": "dbc_company_id",
            "summarizeBy": "none"
          },
          {
            "name": "stopped",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff74c4d7-9525-4216-9a2a-ec3a6685e8a9",
            "sourceColumn": "stopped",
            "summarizeBy": "none"
          },
          {
            "name": "customertype",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3cb6f95-5fea-41ac-8c91-57a409912a27",
            "sourceColumn": "customertype",
            "summarizeBy": "none"
          },
          {
            "name": "sentinel_default_user_override",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b60aafbf-0b21-482b-9de6-cd9f035b41a0",
            "sourceColumn": "sentinel_default_user_override",
            "summarizeBy": "none"
          },
          {
            "name": "ref",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7e6e905-4740-4206-a9b4-be9b3dc747fe",
            "sourceColumn": "ref",
            "summarizeBy": "none"
          },
          {
            "name": "ticket_invoices_for_each_site",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "83cd055c-88a6-45b4-8296-4a6d6a56b4a6",
            "sourceColumn": "ticket_invoices_for_each_site",
            "summarizeBy": "none"
          },
          {
            "name": "is_vip",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "a41d07a4-93ac-4b23-941a-f85a49fe5a81",
            "sourceColumn": "is_vip",
            "summarizeBy": "none"
          },
          {
            "name": "taxable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "b1e21f99-6555-49b2-acb2-5dc2cebabf26",
            "sourceColumn": "taxable",
            "summarizeBy": "none"
          },
          {
            "name": "percentage_to_survey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20cb3ae2-9dd9-44dd-912c-36329a519d00",
            "sourceColumn": "percentage_to_survey",
            "summarizeBy": "none"
          },
          {
            "name": "notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9d2a120-d320-4fe2-87cb-2c8e2ccf1abf",
            "sourceColumn": "notes",
            "summarizeBy": "none"
          },
          {
            "name": "qbo_company_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe360696-c01a-4be3-a7d9-63414c81d2c8",
            "sourceColumn": "qbo_company_id",
            "summarizeBy": "none"
          },
          {
            "name": "servicenow_validated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "39447a78-562b-4119-9ae5-fbadd5c51da1",
            "sourceColumn": "servicenow_validated",
            "summarizeBy": "none"
          },
          {
            "name": "jira_validated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d5e153d7-36cd-424b-b219-767ad5cd62d2",
            "sourceColumn": "jira_validated",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b80d486c-a37e-430e-ba7c-a856aef2f4ba",
        "partitions": [
          {
            "name": "Clients",
            "mode": "import",
            "queryGroup": "01 API returns\\01-00 SingleQuery",
            "source": {
              "expression": [
                "let",
                "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
                "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
                "        loginURL = #\"HaloITSM-AuthURL\",",
                "        TokenUri = \"/token\", // which domain is this a token for",
                "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
                "        TokenResponse = Json.Document(",
                "            Web.Contents(loginURL",
                "\t\t\t    , [RelativePath = TokenUri",
                "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
                "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
                "\t\t\t    ]",
                "            ) // end web contents",
                "        ), // end json",
                "        generatedToken = TokenResponse[access_token] // assign token value",
                "    in",
                "    generatedToken,",
                "    myToken = makeToken(",
                "                        #\"HaloITSM-ResourceURL\"",
                "                        , #\"HaloITSM-ClientID\"",
                "                        , #\"HaloITSM-Secret\"",
                "                    ) // end makeToken",
                "    , ",
                "    // Ping API for json",
                "    Source = Json.Document(",
                "        Web.Contents(",
                "            #\"HaloITSM-ResourceURL\"",
                "            , [",
                "                RelativePath = \"Client\"",
                "                , Headers = [",
                "                    Authorization = \"Bearer \" ",
                "                    &  myToken",
                "                ]",
                "            ]",
                "        )",
                "    )[clients],",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"name\", \"toplevel_id\", \"toplevel_name\", \"inactive\", \"colour\", \"confirmemail\", \"actionemail\", \"clearemail\", \"messagegroup_id\", \"from_address_override\", \"mailbox_override\", \"default_mailbox_id\", \"item_tax_code\", \"service_tax_code\", \"prepay_tax_code\", \"contract_tax_code\", \"pritech\", \"sectech\", \"accountmanagertech\", \"use\", \"xero_tenant_id\", \"overridepdftemplateinvoice\", \"kashflow_tenant_id\", \"client_to_invoice\", \"invoiceduedaysextraclient\", \"itglue_id\", \"clientcurrency\", \"sentinel_subscription_id\", \"sentinel_workspace_name\", \"sentinel_resource_group_name\", \"default_currency_code\", \"client_to_invoice_recurring\", \"dbc_company_id\", \"stopped\", \"customertype\", \"sentinel_default_user_override\", \"ref\", \"ticket_invoices_for_each_site\", \"is_vip\", \"taxable\", \"percentage_to_survey\", \"notes\", \"qbo_company_id\", \"servicenow_validated\", \"jira_validated\"}, {\"id\", \"name\", \"toplevel_id\", \"toplevel_name\", \"inactive\", \"colour\", \"confirmemail\", \"actionemail\", \"clearemail\", \"messagegroup_id\", \"from_address_override\", \"mailbox_override\", \"default_mailbox_id\", \"item_tax_code\", \"service_tax_code\", \"prepay_tax_code\", \"contract_tax_code\", \"pritech\", \"sectech\", \"accountmanagertech\", \"use\", \"xero_tenant_id\", \"overridepdftemplateinvoice\", \"kashflow_tenant_id\", \"client_to_invoice\", \"invoiceduedaysextraclient\", \"itglue_id\", \"clientcurrency\", \"sentinel_subscription_id\", \"sentinel_workspace_name\", \"sentinel_resource_group_name\", \"default_currency_code\", \"client_to_invoice_recurring\", \"dbc_company_id\", \"stopped\", \"customertype\", \"sentinel_default_user_override\", \"ref\", \"ticket_invoices_for_each_site\", \"is_vip\", \"taxable\", \"percentage_to_survey\", \"notes\", \"qbo_company_id\", \"servicenow_validated\", \"jira_validated\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Column1\",{{\"inactive\", type logical}, {\"ticket_invoices_for_each_site\", type logical}, {\"is_vip\", type logical}, {\"taxable\", type logical}, {\"servicenow_validated\", type logical}, {\"jira_validated\", type logical}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"id\", \"client id\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sites",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "site id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edcce832-3d07-48bb-b9ba-b23c14c4cccf",
            "sourceColumn": "site id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6863c085-3c6e-4179-a0e3-b39c7fa4e061",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "client_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1909cc10-3d75-4714-9f66-4a7634c72e11",
            "sourceColumn": "client_id",
            "summarizeBy": "none"
          },
          {
            "name": "client_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e936a5df-96c8-4816-a9e7-814b729d0a86",
            "sourceColumn": "client_name",
            "summarizeBy": "none"
          },
          {
            "name": "clientsite_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15fa9e55-24b4-45f7-9091-137dd8e07aea",
            "sourceColumn": "clientsite_name",
            "summarizeBy": "none"
          },
          {
            "name": "inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "47830df7-423e-4a78-a110-63693df7269a",
            "sourceColumn": "inactive",
            "summarizeBy": "none"
          },
          {
            "name": "sla_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d7ab04d-b85c-4c45-b03e-75086dcb228c",
            "sourceColumn": "sla_id",
            "summarizeBy": "none"
          },
          {
            "name": "phonenumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f12c9c57-4373-45cd-bd61-bd6a3fbc11b6",
            "sourceColumn": "phonenumber",
            "summarizeBy": "none"
          },
          {
            "name": "colour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea57c1e9-0e86-4fb8-a6cb-be9fe77c4027",
            "sourceColumn": "colour",
            "summarizeBy": "none"
          },
          {
            "name": "timezone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b0cd34e-9e1c-4486-8939-c11368abad70",
            "sourceColumn": "timezone",
            "summarizeBy": "none"
          },
          {
            "name": "invoice_address_isdelivery",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "cdb7190e-8db0-4b81-8155-4246a3c7e754",
            "sourceColumn": "invoice_address_isdelivery",
            "summarizeBy": "none"
          },
          {
            "name": "isstocklocation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "41377c55-de31-4a0e-a8c6-28e6f1cfe5cb",
            "sourceColumn": "isstocklocation",
            "summarizeBy": "none"
          },
          {
            "name": "messagegroup_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90b9f3aa-9870-45f8-b5fb-ee7b04ffdf62",
            "sourceColumn": "messagegroup_id",
            "summarizeBy": "none"
          },
          {
            "name": "use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "248c5f20-1700-427f-ab7b-96c3f216cbbe",
            "sourceColumn": "use",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "00c4dc7c-ef0e-48f7-923c-24ce3c0353f4",
        "partitions": [
          {
            "name": "Sites",
            "mode": "import",
            "queryGroup": "01 API returns\\01-01 Paginated",
            "source": {
              "expression": [
                "let",
                "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
                "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
                "        loginURL = #\"HaloITSM-AuthURL\",",
                "        TokenUri = \"/token\", // which domain is this a token for",
                "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
                "        TokenResponse = Json.Document(",
                "            Web.Contents(loginURL",
                "\t\t\t    , [RelativePath = TokenUri",
                "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
                "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
                "\t\t\t    ]",
                "            ) // end web contents",
                "        ), // end json",
                "        generatedToken = TokenResponse[access_token] // assign token value",
                "    in",
                "    generatedToken,",
                "    myToken = makeToken(",
                "                        #\"HaloITSM-ResourceURL\"",
                "                        , #\"HaloITSM-ClientID\"",
                "                        , #\"HaloITSM-Secret\"",
                "                    ) // end makeToken",
                "    , ",
                "    // Ping API for json",
                "    Source = Json.Document(",
                "        Web.Contents(",
                "            #\"HaloITSM-ResourceURL\"",
                "            , [",
                "                RelativePath = \"Site\"",
                "                , Headers = [",
                "                    Authorization = \"Bearer \" ",
                "                    &  myToken",
                "                ]",
                "            ]",
                "        )",
                "    )[sites],",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"name\", \"client_id\", \"client_name\", \"clientsite_name\", \"inactive\", \"sla_id\", \"phonenumber\", \"colour\", \"timezone\", \"invoice_address_isdelivery\", \"isstocklocation\", \"messagegroup_id\", \"use\"}, {\"id\", \"name\", \"client_id\", \"client_name\", \"clientsite_name\", \"inactive\", \"sla_id\", \"phonenumber\", \"colour\", \"timezone\", \"invoice_address_isdelivery\", \"isstocklocation\", \"messagegroup_id\", \"use\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Column1\",{{\"inactive\", type logical}, {\"invoice_address_isdelivery\", type logical}, {\"isstocklocation\", type logical}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"id\", \"site id\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Suppliers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "supplier id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6545773e-6d06-48e6-8923-4d9fa49d3f45",
            "sourceColumn": "supplier id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94eb3100-5d6d-474e-9855-f237b4fb1c67",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "logo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a797c90-012f-4901-b567-1693cfb271b5",
            "sourceColumn": "logo",
            "summarizeBy": "none"
          },
          {
            "name": "toplevel_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d64fbb4-9f80-42f9-a77a-ba17c8d284a1",
            "sourceColumn": "toplevel_id",
            "summarizeBy": "none"
          },
          {
            "name": "toplevel_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68429066-10b5-490c-b40a-b969e261ba24",
            "sourceColumn": "toplevel_name",
            "summarizeBy": "none"
          },
          {
            "name": "contact_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "508c28f9-eacd-4ba2-be6a-fd216fa488c6",
            "sourceColumn": "contact_name",
            "summarizeBy": "none"
          },
          {
            "name": "email_address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6c3c62f-7693-42cb-8627-e7788044538b",
            "sourceColumn": "email_address",
            "summarizeBy": "none"
          },
          {
            "name": "support_email_address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01dbedf1-379c-48ba-97d5-75eff00bed6f",
            "sourceColumn": "support_email_address",
            "summarizeBy": "none"
          },
          {
            "name": "phone_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5344345b-d636-405c-9668-d630d82e592f",
            "sourceColumn": "phone_number",
            "summarizeBy": "none"
          },
          {
            "name": "inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "205c1cf8-4e4b-483d-9b30-33dfadbac11f",
            "sourceColumn": "inactive",
            "summarizeBy": "none"
          },
          {
            "name": "emailtemplate_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1e5b9ce-3e21-463e-8b69-fa6a49fb5fde",
            "sourceColumn": "emailtemplate_id",
            "summarizeBy": "none"
          },
          {
            "name": "thirdpartynhdapiurl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd6ae906-0281-4b54-90eb-25fc55f55f6c",
            "sourceColumn": "thirdpartynhdapiurl",
            "summarizeBy": "none"
          },
          {
            "name": "contract_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "478ca34d-0e0e-42b7-8d59-1af4b3209ff7",
            "sourceColumn": "contract_count",
            "summarizeBy": "none"
          },
          {
            "name": "use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "377a8709-af6e-4f89-bb17-ef71ce5301f4",
            "sourceColumn": "use",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_mailbox_override",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d1a59f7-e608-419c-af58-77b029668ab9",
            "sourceColumn": "supplier_mailbox_override",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_mailbox_address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64eaad24-96fb-4b8f-be03-fd19eee62a3f",
            "sourceColumn": "supplier_mailbox_address",
            "summarizeBy": "none"
          },
          {
            "name": "qbo_company_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "416c2142-8aa1-418a-b319-e4c86bc78494",
            "sourceColumn": "qbo_company_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "371e79b1-170f-4873-a00d-9c4428a071a4",
        "partitions": [
          {
            "name": "Suppliers",
            "mode": "import",
            "queryGroup": "01 API returns\\01-00 SingleQuery",
            "source": {
              "expression": [
                "let",
                "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
                "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
                "        loginURL = #\"HaloITSM-AuthURL\",",
                "        TokenUri = \"/token\", // which domain is this a token for",
                "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
                "        TokenResponse = Json.Document(",
                "            Web.Contents(loginURL",
                "\t\t\t    , [RelativePath = TokenUri",
                "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
                "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
                "\t\t\t    ]",
                "            ) // end web contents",
                "        ), // end json",
                "        generatedToken = TokenResponse[access_token] // assign token value",
                "    in",
                "    generatedToken,",
                "    myToken = makeToken(",
                "                        #\"HaloITSM-ResourceURL\"",
                "                        , #\"HaloITSM-ClientID\"",
                "                        , #\"HaloITSM-Secret\"",
                "                    ) // end makeToken",
                "    , ",
                "    // Ping API for json",
                "    Source = Json.Document(",
                "        Web.Contents(",
                "            #\"HaloITSM-ResourceURL\"",
                "            , [",
                "                RelativePath = \"Supplier\"",
                "                , Headers = [",
                "                    Authorization = \"Bearer \" ",
                "                    &  myToken",
                "                ]",
                "            ]",
                "        )",
                "    )[suppliers],",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"name\", \"logo\", \"toplevel_id\", \"toplevel_name\", \"contact_name\", \"email_address\", \"support_email_address\", \"phone_number\", \"inactive\", \"emailtemplate_id\", \"thirdpartynhdapiurl\", \"contract_count\", \"use\", \"supplier_mailbox_override\", \"supplier_mailbox_address\", \"qbo_company_id\"}, {\"id\", \"name\", \"logo\", \"toplevel_id\", \"toplevel_name\", \"contact_name\", \"email_address\", \"support_email_address\", \"phone_number\", \"inactive\", \"emailtemplate_id\", \"thirdpartynhdapiurl\", \"contract_count\", \"use\", \"supplier_mailbox_override\", \"supplier_mailbox_address\", \"qbo_company_id\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Column1\",{{\"id\", \"supplier id\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tickets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ticket id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cea39e1f-08f8-4c16-bf21-ece26c8a5420",
            "sourceColumn": "ticket id",
            "summarizeBy": "none"
          },
          {
            "name": "dateoccurred",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "11d8ac00-1665-4f9d-aae5-7afec56c438d",
            "sourceColumn": "dateoccurred",
            "summarizeBy": "none"
          },
          {
            "name": "summary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62357112-8ef0-4c2f-a283-2f678a6edea0",
            "sourceColumn": "summary",
            "summarizeBy": "none"
          },
          {
            "name": "details",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a986520-f2dc-4392-9cf3-f1d32d75bd4d",
            "sourceColumn": "details",
            "summarizeBy": "none"
          },
          {
            "name": "status_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb7d6979-0993-4443-87f3-f241f9f1aec2",
            "sourceColumn": "status_id",
            "summarizeBy": "none"
          },
          {
            "name": "tickettype_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9730b70d-bf38-480f-acaa-cd07e860ca3b",
            "sourceColumn": "tickettype_id",
            "summarizeBy": "none"
          },
          {
            "name": "sla_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a56976d1-14dd-4ae0-9a93-605a1e8e94a3",
            "sourceColumn": "sla_id",
            "summarizeBy": "none"
          },
          {
            "name": "priority_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2489a6f-1f41-49a6-acff-4ee656da523b",
            "sourceColumn": "priority_id",
            "summarizeBy": "none"
          },
          {
            "name": "client_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "daebd041-265f-4761-b8f0-6b8b9a137756",
            "sourceColumn": "client_id",
            "summarizeBy": "none"
          },
          {
            "name": "client_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d1b061a-fe91-4e5c-ac2a-8bf217a7eae9",
            "sourceColumn": "client_name",
            "summarizeBy": "none"
          },
          {
            "name": "site_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "765a553b-3773-4e05-b1e9-4131d9ab804a",
            "sourceColumn": "site_id",
            "summarizeBy": "none"
          },
          {
            "name": "site_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d5b5a94-9dae-495c-abbc-6b5e571d46a6",
            "sourceColumn": "site_name",
            "summarizeBy": "none"
          },
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15f5576d-e449-4c71-a96e-dcf67c5adc62",
            "sourceColumn": "user_id",
            "summarizeBy": "none"
          },
          {
            "name": "user_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d720e9c-a4be-4fb1-ab82-d8e58c79d129",
            "sourceColumn": "user_name",
            "summarizeBy": "none"
          },
          {
            "name": "team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8de3a7a8-e826-440c-86be-7e2f274e5597",
            "sourceColumn": "team",
            "summarizeBy": "none"
          },
          {
            "name": "agent_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2eb3ae64-a6c9-406a-9f7b-c6522b56cbc7",
            "sourceColumn": "agent_id",
            "summarizeBy": "none"
          },
          {
            "name": "category_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd49a5e5-bc6a-424e-9693-2bdc199fbc75",
            "sourceColumn": "category_1",
            "summarizeBy": "none"
          },
          {
            "name": "category_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a8ffc00-80a7-4b63-92a8-dead682c1d2c",
            "sourceColumn": "category_2",
            "summarizeBy": "none"
          },
          {
            "name": "category_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "710a9f75-d551-46e0-801f-4e783efc247a",
            "sourceColumn": "category_3",
            "summarizeBy": "none"
          },
          {
            "name": "category_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "397789bd-67d5-491d-a9a7-98d1ee5405dd",
            "sourceColumn": "category_4",
            "summarizeBy": "none"
          },
          {
            "name": "estimate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "875ef6c8-d4ed-44e9-9acd-7fed187d46db",
            "sourceColumn": "estimate",
            "summarizeBy": "none"
          },
          {
            "name": "estimatedays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0e36fb1-3e56-42ee-a332-98776d5092ec",
            "sourceColumn": "estimatedays",
            "summarizeBy": "none"
          },
          {
            "name": "parent_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b844cfe-3d70-4881-829d-8d747c558ae4",
            "sourceColumn": "parent_id",
            "summarizeBy": "none"
          },
          {
            "name": "child_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5600fc3e-6af9-4529-98b2-dbd3285dfe60",
            "sourceColumn": "child_count",
            "summarizeBy": "none"
          },
          {
            "name": "attachment_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8347bf5-819e-4edc-a049-2be77df44060",
            "sourceColumn": "attachment_count",
            "summarizeBy": "none"
          },
          {
            "name": "flagged",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c70091f-904a-4968-aeb2-9fbbe8058ee4",
            "sourceColumn": "flagged",
            "summarizeBy": "none"
          },
          {
            "name": "read",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd777491-ebda-454e-9b0b-a1a59b392ce1",
            "sourceColumn": "read",
            "summarizeBy": "none"
          },
          {
            "name": "enduserstatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "853b4e74-56c0-48dc-9a2b-433719c1d838",
            "sourceColumn": "enduserstatus",
            "summarizeBy": "none"
          },
          {
            "name": "onhold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3a7db0d2-1bd2-47d7-b1c4-762cab1fe395",
            "sourceColumn": "onhold",
            "summarizeBy": "none"
          },
          {
            "name": "respondbydate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "94ba2654-dfc0-4178-9262-a46216a3fd07",
            "sourceColumn": "respondbydate",
            "summarizeBy": "none"
          },
          {
            "name": "fixbydate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "11c195c3-2104-4b23-8e88-795f6ddf11a3",
            "sourceColumn": "fixbydate",
            "summarizeBy": "none"
          },
          {
            "name": "dateassigned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5369ef50-d05e-4845-976b-221148a46168",
            "sourceColumn": "dateassigned",
            "summarizeBy": "none"
          },
          {
            "name": "excludefromsla",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0cd273fa-8837-4533-aa15-3ede882fd932",
            "sourceColumn": "excludefromsla",
            "summarizeBy": "none"
          },
          {
            "name": "slaholdtime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac8091bf-4d63-4718-9276-14c219efb02c",
            "sourceColumn": "slaholdtime",
            "summarizeBy": "none"
          },
          {
            "name": "site_timezone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86c04690-5f8e-48b3-ad71-d81e91f6b7d3",
            "sourceColumn": "site_timezone",
            "summarizeBy": "none"
          },
          {
            "name": "lastactiondate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c5a9eff9-1af0-483a-9e0a-dae40e9b7beb",
            "sourceColumn": "lastactiondate",
            "summarizeBy": "none"
          },
          {
            "name": "organisation_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95c301c3-0a79-41c3-8324-14917ecffc5b",
            "sourceColumn": "organisation_id",
            "summarizeBy": "none"
          },
          {
            "name": "department_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75b6a50c-0fec-4903-a9fd-dfbd01dfd781",
            "sourceColumn": "department_id",
            "summarizeBy": "none"
          },
          {
            "name": "reportedby",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0120fb93-c991-4151-9842-8d48664e83b6",
            "sourceColumn": "reportedby",
            "summarizeBy": "none"
          },
          {
            "name": "user_email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc580cbf-6622-456b-8f70-137d233cc753",
            "sourceColumn": "user_email",
            "summarizeBy": "none"
          },
          {
            "name": "emailtolist",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca9fffd5-576d-47df-8895-590d35c2b8c3",
            "sourceColumn": "emailtolist",
            "summarizeBy": "none"
          },
          {
            "name": "emailtolistsupplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "520bc4e4-9ceb-4a93-85ce-f51d230ef9a3",
            "sourceColumn": "emailtolistsupplier",
            "summarizeBy": "none"
          },
          {
            "name": "emailcclist",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "623d9933-d4cd-4282-822e-a8761a4135fa",
            "sourceColumn": "emailcclist",
            "summarizeBy": "none"
          },
          {
            "name": "emailcclistsupplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9c3f0c0-a8ea-4a06-bd4e-4e1a4d8167f5",
            "sourceColumn": "emailcclistsupplier",
            "summarizeBy": "none"
          },
          {
            "name": "matched_kb_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b104e1a-6f93-45f1-bda2-827df945069b",
            "sourceColumn": "matched_kb_id",
            "summarizeBy": "none"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c97768ae-6d27-4213-8de4-e647614472ee",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "release_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0954082d-3277-40cd-8f3a-3f5e2522c8ea",
            "sourceColumn": "release_id",
            "summarizeBy": "none"
          },
          {
            "name": "release2_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2e74612-2a79-42ba-873b-9c1977225d5a",
            "sourceColumn": "release2_id",
            "summarizeBy": "none"
          },
          {
            "name": "release3_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc25311e-09da-4106-8a9a-c95c5e3ea68f",
            "sourceColumn": "release3_id",
            "summarizeBy": "none"
          },
          {
            "name": "inventory_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03491951-0cdf-4624-b924-b2021d8f1825",
            "sourceColumn": "inventory_number",
            "summarizeBy": "none"
          },
          {
            "name": "workflow_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efd19ccf-e6ff-4b91-9dfe-35de32ccd7c4",
            "sourceColumn": "workflow_id",
            "summarizeBy": "none"
          },
          {
            "name": "workflow_step",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65783e75-8931-41ee-962c-4ca6e6f84606",
            "sourceColumn": "workflow_step",
            "summarizeBy": "none"
          },
          {
            "name": "hasbeenclosed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c7b1c6bc-0c10-4590-a576-ff418d4d3dc9",
            "sourceColumn": "hasbeenclosed",
            "summarizeBy": "none"
          },
          {
            "name": "is_vip",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0c0e52ff-6b3a-4115-be26-713e2c8bc9c1",
            "sourceColumn": "is_vip",
            "summarizeBy": "none"
          },
          {
            "name": "isimportantcontact",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "de66c957-ad6a-46af-b71f-00a2b175fbec",
            "sourceColumn": "isimportantcontact",
            "summarizeBy": "none"
          },
          {
            "name": "inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "47b10b2b-081e-487b-9406-acd80ea4b442",
            "sourceColumn": "inactive",
            "summarizeBy": "none"
          },
          {
            "name": "impact",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdc539c6-4c44-4808-ac86-52f24767646f",
            "sourceColumn": "impact",
            "summarizeBy": "none"
          },
          {
            "name": "urgency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5753f2ab-74b3-4910-9c3e-f355441e1c58",
            "sourceColumn": "urgency",
            "summarizeBy": "none"
          },
          {
            "name": "oppcompanyname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e54b19a-23ac-426e-8554-cfaebe330520",
            "sourceColumn": "oppcompanyname",
            "summarizeBy": "none"
          },
          {
            "name": "oppvalueadjusted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58aa2540-5ed0-4abe-b7e7-811a324a3fcb",
            "sourceColumn": "oppvalueadjusted",
            "summarizeBy": "none"
          },
          {
            "name": "cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5edbe630-d60b-4d82-bf27-9c83cde0cdcc",
            "sourceColumn": "cost",
            "summarizeBy": "none"
          },
          {
            "name": "quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e62695c4-2831-4a73-91a1-8ecc6e2ec1a3",
            "sourceColumn": "quantity",
            "summarizeBy": "none"
          },
          {
            "name": "projecttimebudget",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a509498d-9f65-4330-9e8c-3d1bf6b458fd",
            "sourceColumn": "projecttimebudget",
            "summarizeBy": "none"
          },
          {
            "name": "projectmoneybudget",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17364ece-a815-4ef2-9574-356d8a0c46c0",
            "sourceColumn": "projectmoneybudget",
            "summarizeBy": "none"
          },
          {
            "name": "projecttimeactual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1022e2c-8789-43dc-84ba-683eccea10bd",
            "sourceColumn": "projecttimeactual",
            "summarizeBy": "none"
          },
          {
            "name": "projectmoneyactual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d50f3c22-eefa-40da-966e-dbff973bae6a",
            "sourceColumn": "projectmoneyactual",
            "summarizeBy": "none"
          },
          {
            "name": "userdef1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65a7cc29-12ef-45d1-9b26-7b0945cc6687",
            "sourceColumn": "userdef1",
            "summarizeBy": "none"
          },
          {
            "name": "userdef2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45dc5965-0405-4f2e-919d-cf59b674011a",
            "sourceColumn": "userdef2",
            "summarizeBy": "none"
          },
          {
            "name": "userdef3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1eda894c-ebdd-43ff-83a4-bf433a175909",
            "sourceColumn": "userdef3",
            "summarizeBy": "none"
          },
          {
            "name": "userdef4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "563d80b2-3068-4994-8ca0-5cc92b791aa7",
            "sourceColumn": "userdef4",
            "summarizeBy": "none"
          },
          {
            "name": "userdef5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65fa21df-14ca-4d91-9e4f-c351c22dd29b",
            "sourceColumn": "userdef5",
            "summarizeBy": "none"
          },
          {
            "name": "source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e00d30c6-bdff-4641-a6cc-d248b04c5d98",
            "sourceColumn": "source",
            "summarizeBy": "none"
          },
          {
            "name": "release_important",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "fdcfb329-597c-4667-a8f6-7ad487b36ea7",
            "sourceColumn": "release_important",
            "summarizeBy": "none"
          },
          {
            "name": "releasenotegroup_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95b1130e-c31b-4377-b763-336a97e43cd8",
            "sourceColumn": "releasenotegroup_id",
            "summarizeBy": "none"
          },
          {
            "name": "third_party_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f009df4-a3df-4935-bf99-07f815400f5d",
            "sourceColumn": "third_party_id",
            "summarizeBy": "none"
          },
          {
            "name": "third_party_id_string",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44d2fd9f-9d21-4a48-ae37-93f8902de7fd",
            "sourceColumn": "third_party_id_string",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29708a9b-5227-43e6-9c37-8e63e25734f3",
            "sourceColumn": "supplier_status",
            "summarizeBy": "none"
          },
          {
            "name": "appointment_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98f1cd34-64d7-4bec-8d2c-e013b075e928",
            "sourceColumn": "appointment_type",
            "summarizeBy": "none"
          },
          {
            "name": "section_timezone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "953e0ccf-ba27-4b45-81e8-fd3075835175",
            "sourceColumn": "section_timezone",
            "summarizeBy": "none"
          },
          {
            "name": "projectinternaltask",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "adee88d3-9912-4fea-9e2b-2fe025dabde0",
            "sourceColumn": "projectinternaltask",
            "summarizeBy": "none"
          },
          {
            "name": "impactlevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60b92a19-ed9f-404a-b545-9df8f2c3f0e6",
            "sourceColumn": "impactlevel",
            "summarizeBy": "none"
          },
          {
            "name": "use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "245778c5-b237-4c74-b05d-6cc664634a91",
            "sourceColumn": "use",
            "summarizeBy": "none"
          },
          {
            "name": "maximumRestrictedPriority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17a4eefb-ac2b-4142-90df-15a615d44fa9",
            "sourceColumn": "maximumRestrictedPriority",
            "summarizeBy": "none"
          },
          {
            "name": "idsummary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0f4e232-046a-410c-bbce-df42cd5f1cd6",
            "sourceColumn": "idsummary",
            "summarizeBy": "none"
          },
          {
            "name": "ticketage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab7b67d1-ae03-4c04-8bd8-47aadbb76fbd",
            "sourceColumn": "ticketage",
            "summarizeBy": "none"
          },
          {
            "name": "useful_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f051565e-44ee-469d-80f2-5ad99539481c",
            "sourceColumn": "useful_count",
            "summarizeBy": "none"
          },
          {
            "name": "notuseful_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b27f63bb-ca04-4d65-93ed-89cd7b33d00e",
            "sourceColumn": "notuseful_count",
            "summarizeBy": "none"
          },
          {
            "name": "itil_requesttype_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e71abeac-2e1e-4aeb-8269-d671f5011dbe",
            "sourceColumn": "itil_requesttype_id",
            "summarizeBy": "none"
          },
          {
            "name": "closed_in_integration_system",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "7342329d-da4f-4d9f-9802-5e26c3ada1c4",
            "sourceColumn": "closed_in_integration_system",
            "summarizeBy": "none"
          },
          {
            "name": "approval_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "827834f4-f7e3-45b3-9437-0a212acfe2b1",
            "sourceColumn": "approval_status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4e544384-e753-41a1-b3df-268e23a11e6f",
        "partitions": [
          {
            "name": "Tickets",
            "mode": "import",
            "queryGroup": "03 Report Tables",
            "source": {
              "expression": [
                "let",
                "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
                "    makeToken = TicketsRaw,",
                "    #\"Converted to Table\" = Table.FromList(makeToken, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"dateoccurred\", \"summary\", \"details\", \"status_id\", \"tickettype_id\", \"sla_id\", \"priority_id\", \"client_id\", \"client_name\", \"site_id\", \"site_name\", \"user_id\", \"user_name\", \"team\", \"agent_id\", \"category_1\", \"category_2\", \"category_3\", \"category_4\", \"estimate\", \"estimatedays\", \"parent_id\", \"child_count\", \"attachment_count\", \"flagged\", \"read\", \"enduserstatus\", \"onhold\", \"respondbydate\", \"fixbydate\", \"dateassigned\", \"excludefromsla\", \"slaholdtime\", \"site_timezone\", \"lastactiondate\", \"organisation_id\", \"department_id\", \"reportedby\", \"user_email\", \"emailtolist\", \"emailtolistsupplier\", \"emailcclist\", \"emailcclistsupplier\", \"matched_kb_id\", \"product_id\", \"release_id\", \"release2_id\", \"release3_id\", \"lastincomingemail\", \"inventory_number\", \"workflow_id\", \"workflow_step\", \"hasbeenclosed\", \"is_vip\", \"isimportantcontact\", \"inactive\", \"impact\", \"urgency\", \"startdate\", \"starttime\", \"starttimeslot\", \"targetdate\", \"targettime\", \"targettimeslot\", \"deadlinedate\", \"oppcompanyname\", \"oppvalueadjusted\", \"cost\", \"quantity\", \"projecttimebudget\", \"projectmoneybudget\", \"projecttimeactual\", \"projectmoneyactual\", \"userdef1\", \"userdef2\", \"userdef3\", \"userdef4\", \"userdef5\", \"source\", \"release_important\", \"releasenotegroup_id\", \"third_party_id\", \"third_party_id_string\", \"supplier_status\", \"appointment_type\", \"section_timezone\", \"projectinternaltask\", \"impactlevel\", \"use\", \"maximumRestrictedPriority\", \"idsummary\", \"ticketage\", \"useful_count\", \"notuseful_count\", \"itil_requesttype_id\", \"closed_in_integration_system\", \"approval_status\"}, {\"id\", \"dateoccurred\", \"summary\", \"details\", \"status_id\", \"tickettype_id\", \"sla_id\", \"priority_id\", \"client_id\", \"client_name\", \"site_id\", \"site_name\", \"user_id\", \"user_name\", \"team\", \"agent_id\", \"category_1\", \"category_2\", \"category_3\", \"category_4\", \"estimate\", \"estimatedays\", \"parent_id\", \"child_count\", \"attachment_count\", \"flagged\", \"read\", \"enduserstatus\", \"onhold\", \"respondbydate\", \"fixbydate\", \"dateassigned\", \"excludefromsla\", \"slaholdtime\", \"site_timezone\", \"lastactiondate\", \"organisation_id\", \"department_id\", \"reportedby\", \"user_email\", \"emailtolist\", \"emailtolistsupplier\", \"emailcclist\", \"emailcclistsupplier\", \"matched_kb_id\", \"product_id\", \"release_id\", \"release2_id\", \"release3_id\", \"lastincomingemail\", \"inventory_number\", \"workflow_id\", \"workflow_step\", \"hasbeenclosed\", \"is_vip\", \"isimportantcontact\", \"inactive\", \"impact\", \"urgency\", \"startdate\", \"starttime\", \"starttimeslot\", \"targetdate\", \"targettime\", \"targettimeslot\", \"deadlinedate\", \"oppcompanyname\", \"oppvalueadjusted\", \"cost\", \"quantity\", \"projecttimebudget\", \"projectmoneybudget\", \"projecttimeactual\", \"projectmoneyactual\", \"userdef1\", \"userdef2\", \"userdef3\", \"userdef4\", \"userdef5\", \"source\", \"release_important\", \"releasenotegroup_id\", \"third_party_id\", \"third_party_id_string\", \"supplier_status\", \"appointment_type\", \"section_timezone\", \"projectinternaltask\", \"impactlevel\", \"use\", \"maximumRestrictedPriority\", \"idsummary\", \"ticketage\", \"useful_count\", \"notuseful_count\", \"itil_requesttype_id\", \"closed_in_integration_system\", \"approval_status\"}),",
                "    #\"Changed Types - TF and datetimezones\" = Table.TransformColumnTypes(#\"Expanded Column1\",{{\"dateoccurred\", type datetimezone}, {\"respondbydate\", type datetimezone}, {\"fixbydate\", type datetimezone}, {\"dateassigned\", type datetimezone}, {\"onhold\", type logical}, {\"excludefromsla\", type logical}, {\"lastactiondate\", type datetimezone}, {\"hasbeenclosed\", type logical}, {\"is_vip\", type logical}, {\"isimportantcontact\", type logical}, {\"inactive\", type logical}, {\"release_important\", type logical}, {\"projectinternaltask\", type logical}, {\"closed_in_integration_system\", type logical}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Types - TF and datetimezones\",{\"lastincomingemail\", \"startdate\", \"starttime\", \"starttimeslot\", \"targetdate\", \"targettime\", \"targettimeslot\", \"deadlinedate\"}),",
                "    #\"Replaced blank w/ null\" = Table.ReplaceValue(#\"Removed Columns\",\"\",null,Replacer.ReplaceValue,{\"id\", \"dateoccurred\", \"summary\", \"details\", \"status_id\", \"tickettype_id\", \"sla_id\", \"priority_id\", \"client_id\", \"client_name\", \"site_id\", \"site_name\", \"user_id\", \"user_name\", \"team\", \"agent_id\", \"category_1\", \"category_2\", \"category_3\", \"category_4\", \"estimate\", \"estimatedays\", \"parent_id\", \"child_count\", \"attachment_count\", \"flagged\", \"read\", \"enduserstatus\", \"onhold\", \"respondbydate\", \"fixbydate\", \"dateassigned\", \"excludefromsla\", \"slaholdtime\", \"site_timezone\", \"lastactiondate\", \"organisation_id\", \"department_id\", \"reportedby\", \"user_email\", \"emailtolist\", \"emailtolistsupplier\", \"emailcclist\", \"emailcclistsupplier\", \"matched_kb_id\", \"product_id\", \"release_id\", \"release2_id\", \"release3_id\", \"inventory_number\", \"workflow_id\", \"workflow_step\", \"hasbeenclosed\", \"is_vip\", \"isimportantcontact\", \"inactive\", \"impact\", \"urgency\", \"oppcompanyname\", \"oppvalueadjusted\", \"cost\", \"quantity\", \"projecttimebudget\", \"projectmoneybudget\", \"projecttimeactual\", \"projectmoneyactual\", \"userdef1\", \"userdef2\", \"userdef3\", \"userdef4\", \"userdef5\", \"source\", \"release_important\", \"releasenotegroup_id\", \"third_party_id\", \"third_party_id_string\", \"supplier_status\", \"appointment_type\", \"section_timezone\", \"projectinternaltask\", \"impactlevel\", \"use\", \"maximumRestrictedPriority\", \"idsummary\", \"ticketage\", \"useful_count\", \"notuseful_count\", \"itil_requesttype_id\", \"closed_in_integration_system\", \"approval_status\"}),",
                "    #\"Cleaned Text\" = Table.TransformColumns(#\"Replaced blank w/ null\",{{\"details\", Text.Clean, type text}, {\"summary\", Text.Clean, type text}, {\"client_name\", Text.Clean, type text}, {\"site_name\", Text.Clean, type text}, {\"user_name\", Text.Clean, type text}, {\"team\", Text.Clean, type text}, {\"category_1\", Text.Clean, type text}, {\"reportedby\", Text.Clean, type text}, {\"user_email\", Text.Clean, type text}, {\"emailtolist\", Text.Clean, type text}, {\"emailtolistsupplier\", Text.Clean, type text}, {\"emailcclist\", Text.Clean, type text}, {\"oppcompanyname\", Text.Clean, type text}, {\"userdef1\", Text.Clean, type text}, {\"userdef2\", Text.Clean, type text}, {\"idsummary\", Text.Clean, type text}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(Table.TransformColumnTypes(#\"Cleaned Text\", {{\"category_2\", type text}, {\"category_3\", type text}, {\"category_4\", type text}, {\"emailcclistsupplier\", type text}}, \"en-AU\"),{{\"details\", Text.Trim, type text}, {\"summary\", Text.Trim, type text}, {\"client_name\", Text.Trim, type text}, {\"site_name\", Text.Trim, type text}, {\"user_name\", Text.Trim, type text}, {\"team\", Text.Trim, type text}, {\"category_1\", Text.Trim, type text}, {\"reportedby\", Text.Trim, type text}, {\"user_email\", Text.Trim, type text}, {\"emailtolist\", Text.Trim, type text}, {\"emailtolistsupplier\", Text.Trim, type text}, {\"emailcclist\", Text.Trim, type text}, {\"oppcompanyname\", Text.Trim, type text}, {\"userdef1\", Text.Trim, type text}, {\"userdef2\", Text.Trim, type text}, {\"idsummary\", Text.Trim, type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Trimmed Text\",{{\"id\", \"ticket id\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Agents",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "agent id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd3c5627-4ea8-489d-a25b-4511588a9b4d",
            "sourceColumn": "agent id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9c1e4e7-ceab-42aa-b616-e10dd2664984",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a9a539b-5ba9-4edb-99d9-2d0716105302",
            "sourceColumn": "team",
            "summarizeBy": "none"
          },
          {
            "name": "isdisabled",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "bed2be6b-bf62-4371-ba23-4c31d2d0407e",
            "sourceColumn": "isdisabled",
            "summarizeBy": "none"
          },
          {
            "name": "initials",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adcd47b5-3114-4132-a1c1-cdd9009f99b7",
            "sourceColumn": "initials",
            "summarizeBy": "none"
          },
          {
            "name": "firstname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "240af55c-c38e-4b82-a459-98227ceced44",
            "sourceColumn": "firstname",
            "summarizeBy": "none"
          },
          {
            "name": "surname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6898442-08da-434a-857c-5ded5f649046",
            "sourceColumn": "surname",
            "summarizeBy": "none"
          },
          {
            "name": "jobtitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1444939-8709-4c7e-80a2-f15ec4fdf594",
            "sourceColumn": "jobtitle",
            "summarizeBy": "none"
          },
          {
            "name": "exchange_authorized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "e4a9af36-50d5-4241-989d-b0eed24211d0",
            "sourceColumn": "exchange_authorized",
            "summarizeBy": "none"
          },
          {
            "name": "sentinel_authorized",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8d758279-81ec-470c-b791-782f709538d4",
            "sourceColumn": "sentinel_authorized",
            "summarizeBy": "none"
          },
          {
            "name": "licence_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23bd4347-a70c-46be-8eca-583cd4ea685a",
            "sourceColumn": "licence_type",
            "summarizeBy": "none"
          },
          {
            "name": "allowbeyondtrustinvites",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ea952a5-2a39-40dd-aaca-76ba629905f1",
            "sourceColumn": "allowbeyondtrustinvites",
            "summarizeBy": "none"
          },
          {
            "name": "namewithinactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac312ae6-3397-44ba-9b65-c98083214f8c",
            "sourceColumn": "namewithinactive",
            "summarizeBy": "none"
          },
          {
            "name": "enableshifts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "fb2e1e6f-522d-4454-94fe-1e1c76e9fe80",
            "sourceColumn": "enableshifts",
            "summarizeBy": "none"
          },
          {
            "name": "sendemailerrors",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "97d2f95b-b4e6-4fd8-a1cf-3f1e5b256fb3",
            "sourceColumn": "sendemailerrors",
            "summarizeBy": "none"
          },
          {
            "name": "can_approve_purchaseorder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "79935ef9-0866-4298-90b4-17ecfd995b00",
            "sourceColumn": "can_approve_purchaseorder",
            "summarizeBy": "none"
          },
          {
            "name": "can_approve_quote",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "176849d3-8edd-48c1-81f2-54606ce88177",
            "sourceColumn": "can_approve_quote",
            "summarizeBy": "none"
          },
          {
            "name": "email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "471478a7-ea53-4233-8a0a-6b9ac416fab7",
            "sourceColumn": "email",
            "summarizeBy": "none"
          },
          {
            "name": "lastlogindate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "57d00ca9-59c6-470d-be7a-ca105a03e649",
            "sourceColumn": "lastlogindate",
            "summarizeBy": "none"
          },
          {
            "name": "isapiagent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "74fc606c-e839-469b-b77f-02a14d2fef14",
            "sourceColumn": "isapiagent",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "968d6141-c886-4b0d-9eb9-0547f938a6f9",
        "partitions": [
          {
            "name": "Agents",
            "mode": "import",
            "queryGroup": "03 Report Tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Agents Raw\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"agent id\", \"name\", \"team\", \"isdisabled\", \"initials\", \"firstname\", \"surname\", \"jobtitle\", \"exchange_authorized\", \"sentinel_authorized\", \"licence_type\", \"allowbeyondtrustinvites\", \"namewithinactive\", \"enableshifts\", \"sendemailerrors\", \"can_approve_purchaseorder\", \"can_approve_quote\", \"email\", \"lastlogindate\", \"isapiagent\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Agent teams",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "agent id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9ad7052-bdf3-4218-b144-893e22fea904",
            "sourceColumn": "agent id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5fab22b3-44ea-4b4e-8988-6a11e172e2d8",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "team_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bab18e4e-a2af-44ed-87dc-4207ad335623",
            "sourceColumn": "team_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e690a564-122c-4406-b802-ac2061a749a4",
        "partitions": [
          {
            "name": "Agent teams",
            "mode": "import",
            "queryGroup": "03 Report Tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Agents Raw\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"agent id\", \"name\", \"teams\"}),",
                "    #\"Expanded teams\" = Table.ExpandListColumn(#\"Removed Other Columns\", \"teams\"),",
                "    #\"Expanded teams1\" = Table.ExpandRecordColumn(#\"Expanded teams\", \"teams\", {\"team_id\"}, {\"team_id\"})",
                "in",
                "    #\"Expanded teams1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Teams",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "team_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1e9324c-54a7-44ec-80fa-d9ad3bc78822",
            "sourceColumn": "team_id",
            "summarizeBy": "none"
          },
          {
            "name": "guid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07c942a0-0ec2-4643-ab79-4fce0f3bcea2",
            "sourceColumn": "guid",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05b82b60-4965-4052-b9d3-c77a1cc87dfa",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "sequence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02c55098-1a77-4cca-a34b-7c18724e7f01",
            "sourceColumn": "sequence",
            "summarizeBy": "none"
          },
          {
            "name": "forrequests",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "6ec5d45f-85f8-4958-b246-32455dd852f1",
            "sourceColumn": "forrequests",
            "summarizeBy": "none"
          },
          {
            "name": "foropps",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "9615c86e-0344-4f49-b663-78ceb28b6633",
            "sourceColumn": "foropps",
            "summarizeBy": "none"
          },
          {
            "name": "forprojects",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "a5140caa-5e4c-4721-9ab8-31622e26f1a1",
            "sourceColumn": "forprojects",
            "summarizeBy": "none"
          },
          {
            "name": "ticket_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9a54e26-488f-4347-8f4d-3c1b639550e5",
            "sourceColumn": "ticket_count",
            "summarizeBy": "none"
          },
          {
            "name": "department_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb5a68c5-972f-4beb-a748-fbb56dfc4377",
            "sourceColumn": "department_id",
            "summarizeBy": "none"
          },
          {
            "name": "department_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e2a0526-d358-45fd-8a89-32481b645e87",
            "sourceColumn": "department_name",
            "summarizeBy": "none"
          },
          {
            "name": "inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "b5372a7d-03a6-4d72-a647-38d44d17f12e",
            "sourceColumn": "inactive",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4f145061-06a6-4a21-935b-ecdc6a7b0f0d",
        "partitions": [
          {
            "name": "Teams",
            "mode": "import",
            "queryGroup": "01 API returns\\01-00 SingleQuery",
            "source": {
              "expression": [
                "let",
                "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
                "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
                "        loginURL = #\"HaloITSM-AuthURL\",",
                "        TokenUri = \"/token\", // which domain is this a token for",
                "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
                "        TokenResponse = Json.Document(",
                "            Web.Contents(loginURL",
                "\t\t\t    , [RelativePath = TokenUri",
                "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
                "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
                "\t\t\t    ]",
                "            ) // end web contents",
                "        ), // end json",
                "        generatedToken = TokenResponse[access_token] // assign token value",
                "    in",
                "    generatedToken,",
                "    myToken = makeToken(",
                "                        #\"HaloITSM-ResourceURL\"",
                "                        , #\"HaloITSM-ClientID\"",
                "                        , #\"HaloITSM-Secret\"",
                "                    ) // end makeToken",
                "    , ",
                "    // Ping API for json",
                "    Source = Json.Document(",
                "        Web.Contents(",
                "            #\"HaloITSM-ResourceURL\"",
                "            , [",
                "                RelativePath = \"Team\"",
                "                , Headers = [",
                "                    Authorization = \"Bearer \" ",
                "                    &  myToken",
                "                ]",
                "            ]",
                "        )",
                "    ),",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"guid\", \"name\", \"sequence\", \"forrequests\", \"foropps\", \"forprojects\", \"ticket_count\", \"department_id\", \"department_name\", \"inactive\"}, {\"team_id\", \"guid\", \"name\", \"sequence\", \"forrequests\", \"foropps\", \"forprojects\", \"ticket_count\", \"department_id\", \"department_name\", \"inactive\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Column1\",{{\"forprojects\", type logical}, {\"foropps\", type logical}, {\"forrequests\", type logical}, {\"inactive\", type logical}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Statuses",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "status id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebf399d1-a023-40ac-af95-633509ca4a73",
            "sourceColumn": "status id",
            "summarizeBy": "none"
          },
          {
            "name": "guid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5ea2a93-8ba0-453f-bb1d-fbae7ce15370",
            "sourceColumn": "guid",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "82486b6d-1e75-4528-a9f8-4df6b0ac534c",
            "sortByColumn": "Order",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "shortname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "a445b634-998a-4967-aadc-e1a613a6b781",
            "sortByColumn": "Order",
            "sourceColumn": "shortname",
            "summarizeBy": "none"
          },
          {
            "name": "statusemailid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49eef5fc-51bc-4872-9900-24f20f556513",
            "sourceColumn": "statusemailid",
            "summarizeBy": "none"
          },
          {
            "name": "nochangehoursrecurring",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "4000fcd4-be13-44a4-a1d9-f2047c3e1e51",
            "sourceColumn": "nochangehoursrecurring",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "afaa319a-fa20-4469-b61f-3937b26c247c",
            "sortByColumn": "Order",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "External",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c0f53131-b460-4b95-9768-019e287dfd9e",
            "sourceColumn": "External",
            "summarizeBy": "none"
          },
          {
            "name": "Terminal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "fb6cad55-eb9e-4015-a9f2-326e1b498084",
            "sourceColumn": "Terminal",
            "summarizeBy": "none"
          },
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4d7e1d23-62c9-41c9-b020-274ea4da12bc",
            "sourceColumn": "Order",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4a24ed7e-04df-406f-989d-9fe97d1156a8",
        "partitions": [
          {
            "name": "Statuses",
            "mode": "import",
            "queryGroup": "03 Report Tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Statuses Raw\",",
                "    #\"Merged w/ StatusMapping\" = Table.NestedJoin(Source, {\"status id\"}, StatusMapping, {\"status id\"}, \"StatusMapping\", JoinKind.LeftOuter),",
                "    #\"Expanded StatusMapping\" = Table.ExpandTableColumn(#\"Merged w/ StatusMapping\", \"StatusMapping\", {\"Category\", \"External\", \"Order\", \"Terminal\"}, {\"Category\", \"External\", \"Order\", \"Terminal\"})",
                "in",
                "    #\"Expanded StatusMapping\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MeasuresTable",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "46afd73f-4f41-4c4e-8139-6b1b8a1dcd80",
        "measures": [
          {
            "name": "Tickets",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(Tickets[ticket id])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "47c7f8f1-2e89-47b7-aff5-491daccb5d98"
          },
          {
            "name": "Last Refreshed",
            "expression": "FORMAT(NOW(), \"yyyy/mm/dd HH:mm\")",
            "lineageTag": "60b49eef-46e4-417d-b1d1-892b698d8c17"
          }
        ],
        "partitions": [
          {
            "name": "MeasuresTable",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}