{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1805.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"HaloITSM-AuthURL\",\"HaloITSM-ResourceURL\",\"HaloITSM-Tenant\",\"HaloITSM-ClientID\",\"HaloITSM-Secret\",\"GenerateHaloToken\",\"FetchedHaloToken\",\"Items\",\"TicketTypes\",\"Users\",\"Statuses Raw\",\"Clients\",\"Sites\",\"Suppliers\",\"Tickets\",\"Agents Raw\",\"Agents\",\"Agent teams\",\"Teams\",\"StatusMapping\",\"Statuses\",\"MeasuresTable\",\"pageSize\",\"DateDimensionBI\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "HaloITSM-ClientID",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"YOUR-CLIENTID\" meta [IsParameterQuery=true, List={\"YOUR-CLIENTID\"}, DefaultValue=\"YOUR-CLIENTID\", Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "9a8b46bb-abab-4e94-8630-8655c6314bcc",
        "queryGroup": "00 Utilities\\00-00 Params"
      },
      {
        "name": "HaloITSM-AuthURL",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"https://YOUR-TENANT/DOMAIN.nethelpdesk.com/auth\" meta [IsParameterQuery=true, List={\"https://YOUR-TENANT/DOMAIN.nethelpdesk.com/auth\"}, DefaultValue=\"https://YOUR-TENANT/DOMAIN.nethelpdesk.com/auth\", Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d5d10281-e432-486e-9d44-36084f58be4b",
        "queryGroup": "00 Utilities\\00-00 Params"
      },
      {
        "name": "HaloITSM-ResourceURL",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"https://YOUR-TENANT/DOMAIN.nethelpdesk.com/api\" meta [IsParameterQuery=true, List={\"https://YOUR-TENANT/DOMAIN.nethelpdesk.com/api\"}, DefaultValue=\"https://YOUR-TENANT/DOMAIN.nethelpdesk.com/api\", Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "320ac076-ad7d-4b8b-852b-d41830b5bece",
        "queryGroup": "00 Utilities\\00-00 Params"
      },
      {
        "name": "HaloITSM-Secret",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"YOUR-API-SECRET\" meta [IsParameterQuery=true, List={\"YOUR-API-SECRET\"}, DefaultValue=\"YOUR-API-SECRET\", Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "8260996e-c064-43e9-a1c1-fa04b8fff976",
        "queryGroup": "00 Utilities\\00-00 Params"
      },
      {
        "name": "HaloITSM-Tenant",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"YOUR-TENANT/DOMAIN\" meta [IsParameterQuery=true, List={\"YOUR-TENANT/DOMAIN\"}, DefaultValue=\"YOUR-TENANT/DOMAIN\", Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d88db245-5a78-4f88-af54-9c4bf4dfe5e7",
        "queryGroup": "00 Utilities\\00-00 Params"
      },
      {
        "name": "GenerateHaloToken",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
          "        loginURL = #\"HaloITSM-AuthURL\",",
          "        TokenUri = \"/token\", // which domain is this a token for",
          "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
          "        TokenResponse = Json.Document(",
          "            Web.Contents(loginURL",
          "\t\t\t    , [RelativePath = TokenUri",
          "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
          "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
          "\t\t\t    ]",
          "            ) // end web contents",
          "        ), // end json",
          "        generatedToken = TokenResponse[access_token] // assign token value",
          "    in",
          "    generatedToken",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "3c5d662f-cd05-44d8-a1d2-286e1bd31a0f",
        "queryGroup": "00 Utilities\\00-01 Auth Function"
      },
      {
        "name": "FetchedHaloToken",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": [
          "let",
          "    Source = GenerateHaloToken(#\"HaloITSM-AuthURL\", #\"HaloITSM-ClientID\", #\"HaloITSM-Secret\")",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "d7c7d7b9-11bf-4a57-a9b8-7902ba851c0c",
        "queryGroup": "00 Utilities\\00-01 Auth Function"
      },
      {
        "name": "Items",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Record"
          }
        ],
        "description": "Contains nothing, as such not currently used",
        "expression": [
          "let",
          "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
          "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
          "        loginURL = #\"HaloITSM-AuthURL\",",
          "        TokenUri = \"/token\", // which domain is this a token for",
          "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
          "        TokenResponse = Json.Document(",
          "            Web.Contents(loginURL",
          "\t\t\t    , [RelativePath = TokenUri",
          "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
          "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
          "\t\t\t    ]",
          "            ) // end web contents",
          "        ), // end json",
          "        generatedToken = TokenResponse[access_token] // assign token value",
          "    in",
          "    generatedToken,",
          "    myToken = makeToken(",
          "                        #\"HaloITSM-ResourceURL\"",
          "                        , #\"HaloITSM-ClientID\"",
          "                        , #\"HaloITSM-Secret\"",
          "                    ) // end makeToken",
          "    , ",
          "    // Ping API for json",
          "    Source = Json.Document(",
          "        Web.Contents(",
          "            #\"HaloITSM-ResourceURL\"",
          "            , [",
          "                RelativePath = \"Item\"",
          "                , Headers = [",
          "                    Authorization = \"Bearer \" ",
          "                    &  myToken",
          "                ]",
          "            ]",
          "        )",
          "    )",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "c9dc9909-52c6-4945-8456-54b20de396ad",
        "queryGroup": "01 API returns\\01-01 Staging Queries"
      },
      {
        "name": "Agents Raw",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
          "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
          "        loginURL = #\"HaloITSM-AuthURL\",",
          "        TokenUri = \"/token\", // which domain is this a token for",
          "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
          "        TokenResponse = Json.Document(",
          "            Web.Contents(loginURL",
          "\t\t\t    , [RelativePath = TokenUri",
          "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
          "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
          "\t\t\t    ]",
          "            ) // end web contents",
          "        ), // end json",
          "        generatedToken = TokenResponse[access_token] // assign token value",
          "    in",
          "    generatedToken,",
          "    myToken = makeToken(",
          "                        #\"HaloITSM-ResourceURL\"",
          "                        , #\"HaloITSM-ClientID\"",
          "                        , #\"HaloITSM-Secret\"",
          "                    ) // end makeToken",
          "    , ",
          "    // Ping API for json",
          "    Source = Json.Document(",
          "        Web.Contents(",
          "            #\"HaloITSM-ResourceURL\"",
          "            , [",
          "                RelativePath = \"Agent\"",
          "                , Headers = [",
          "                    Authorization = \"Bearer \" ",
          "                    &  myToken",
          "                ]",
          "            ]",
          "        )",
          "    ),",
          "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "    #\"Expanded Column1\" = Table.ExpandRecordColumn(",
          "        #\"Converted to Table\", \"Column1\", {",
          "            \"id\", \"name\", \"team\", \"isdisabled\", \"initials\", \"firstname\", \"surname\", \"colour\", \"jobtitle\", \"sms\", \"extensionnumber\", \"is_agent\", \"teams\", \"departments\", \"linemanager\", \"exchange_authorized\", \"sentinel_authorized\", \"licence_type\", \"use\", \"allowbeyondtrustinvites\", \"namewithinactive\", \"apptsync\", \"enableshifts\", \"sendemailerrors\", \"can_approve_purchaseorder\", \"can_approve_quote\", \"email\", \"lastlogindate\", \"isapiagent\"",
          "        }",
          "        , {",
          "            \"id\", \"name\", \"team\", \"isdisabled\", \"initials\", \"firstname\", \"surname\", \"colour\", \"jobtitle\", \"sms\", \"extensionnumber\", \"is_agent\", \"teams\", \"departments\", \"linemanager\", \"exchange_authorized\", \"sentinel_authorized\", \"licence_type\", \"use\", \"allowbeyondtrustinvites\", \"namewithinactive\", \"apptsync\", \"enableshifts\", \"sendemailerrors\", \"can_approve_purchaseorder\", \"can_approve_quote\", \"email\", \"lastlogindate\", \"isapiagent\"",
          "        }",
          "    ),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded Column1\",{{\"id\", \"agent id\"}}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns\",\"\",null,Replacer.ReplaceValue,{\"agent id\", \"name\", \"team\", \"isdisabled\", \"initials\", \"firstname\", \"surname\", \"colour\", \"jobtitle\", \"sms\", \"extensionnumber\", \"is_agent\", \"teams\", \"departments\", \"linemanager\", \"exchange_authorized\", \"sentinel_authorized\", \"licence_type\", \"use\", \"allowbeyondtrustinvites\", \"namewithinactive\", \"apptsync\", \"enableshifts\", \"sendemailerrors\", \"can_approve_purchaseorder\", \"can_approve_quote\", \"email\", \"lastlogindate\", \"isapiagent\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"isdisabled\", type logical}, {\"exchange_authorized\", type logical}, {\"sentinel_authorized\", type logical}, {\"enableshifts\", type logical}, {\"sendemailerrors\", type logical}, {\"can_approve_purchaseorder\", type logical}, {\"can_approve_quote\", type logical}, {\"isapiagent\", type logical}, {\"lastlogindate\", type datetimezone}, {\"is_agent\", type logical}}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type\",{{\"team\", \"Primary team\"}})",
          "in",
          "    #\"Renamed Columns1\""
        ],
        "kind": "m",
        "lineageTag": "0e616127-781e-438e-a1d9-b34ca25220d5",
        "queryGroup": "01 API returns\\01-01 Staging Queries"
      },
      {
        "name": "StatusMapping",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "description": "this manual table provides higher level categorisations for the statuses in Halo, and some utility toggles",
        "expression": [
          "let",
          "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"lZPNDoIwEIRfhfTMgbb89YgC0cSoUYwHwqFB1CaEHsD4+lKqBk3jyqmbzJftbKeb5wgjG2XSimV/ptFqn4xOjAo7R6SvjsutQSdaD99AtjsYdAboAWiBgoTbV9Gdi040F2t2a0VTta2BpgPtAY7UyElb8pp31cnQxdWYunQtO3EWRsobKOxPsoaDabh6/Fg21Uh5zsRCTVCQgBLGKsE5b8qqrj8mffVhGvPAm1wwSOxMmp94nxl85akjIPD/YZB1omLcXK2FrE1Zs0B/VOevl6Jq61IuzIyvGQJZomCydNpaUP/HXhQP\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"status id\" = _t, Category = _t, External = _t, Terminal = _t, Order = _t]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"status id\", Int64.Type}, {\"Category\", type text}, {\"External\", type logical}, {\"Terminal\", type logical}, {\"Order\", Int64.Type}}),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type\",{{\"status id\", Order.Ascending}})",
          "in",
          "    #\"Sorted Rows\""
        ],
        "kind": "m",
        "lineageTag": "e6ddeac8-04dc-4e30-8539-925a440e6cc7",
        "queryGroup": "02 Mapping tables"
      },
      {
        "name": "Statuses Raw",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
          "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
          "        loginURL = #\"HaloITSM-AuthURL\",",
          "        TokenUri = \"/token\", // which domain is this a token for",
          "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
          "        TokenResponse = Json.Document(",
          "            Web.Contents(loginURL",
          "\t\t\t    , [RelativePath = TokenUri",
          "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
          "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
          "\t\t\t    ]",
          "            ) // end web contents",
          "        ), // end json",
          "        generatedToken = TokenResponse[access_token] // assign token value",
          "    in",
          "    generatedToken,",
          "    myToken = makeToken(",
          "                        #\"HaloITSM-ResourceURL\"",
          "                        , #\"HaloITSM-ClientID\"",
          "                        , #\"HaloITSM-Secret\"",
          "                    ) // end makeToken",
          "    , ",
          "    // Ping API for json",
          "    Source = Json.Document(",
          "        Web.Contents(",
          "            #\"HaloITSM-ResourceURL\"",
          "            , [",
          "                RelativePath = \"Status\"",
          "                , Headers = [",
          "                    Authorization = \"Bearer \" ",
          "                    &  myToken",
          "                ]",
          "            ]",
          "        )",
          "    ),",
          "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"guid\", \"name\", \"shortname\", \"type\", \"sequence\", \"colour\", \"slaaction\", \"showonquickchange\", \"timeuntilloffhold\", \"statuschangeto\", \"statuschangetofreq\", \"useworkinghours\", \"statusemailfreqdays\", \"statusemailid\", \"statusnochangehours\", \"nochangehoursrecurring\", \"statusnochangehoursmanager\", \"statusnochangehoursmanagerrecurring\", \"statusnochangehourssection\", \"statusnochangehourssectionrecurring\", \"nochangetemplate\"}, {\"id\", \"guid\", \"name\", \"shortname\", \"type\", \"sequence\", \"colour\", \"slaaction\", \"showonquickchange\", \"timeuntilloffhold\", \"statuschangeto\", \"statuschangetofreq\", \"useworkinghours\", \"statusemailfreqdays\", \"statusemailid\", \"statusnochangehours\", \"nochangehoursrecurring\", \"statusnochangehoursmanager\", \"statusnochangehoursmanagerrecurring\", \"statusnochangehourssection\", \"statusnochangehourssectionrecurring\", \"nochangetemplate\"}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Column1\",{{\"showonquickchange\", type logical}, {\"statusnochangehourssectionrecurring\", type logical}, {\"statusnochangehoursmanagerrecurring\", type logical}, {\"nochangehoursrecurring\", type logical}, {\"id\", Int64.Type}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"id\", \"status id\"}}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed Columns\",{\"status id\", \"guid\", \"name\"}),",
          "    #\"Sorted Rows\" = Table.Sort(#\"Removed Other Columns\",{{\"status id\", Order.Ascending}})",
          "in",
          "    #\"Sorted Rows\""
        ],
        "kind": "m",
        "lineageTag": "77586c1f-7605-41ba-a91c-7888c20c5c7c",
        "queryGroup": "01 API returns\\01-01 Staging Queries"
      },
      {
        "name": "pageSize",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "description": "number of items per page, for pagined queries",
        "expression": "80 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "16ccb60c-5d9c-447e-b054-db4ba52a0c1f",
        "queryGroup": "00 Utilities\\00-00 Params"
      },
      {
        "name": "Tickets Raw",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
          "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
          "        loginURL = #\"HaloITSM-AuthURL\",",
          "        TokenUri = \"/token\", // which domain is this a token for",
          "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
          "        TokenResponse = Json.Document(",
          "            Web.Contents(loginURL",
          "\t\t\t    , [RelativePath = TokenUri",
          "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
          "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
          "\t\t\t    ]",
          "            ) // end web contents",
          "        ), // end json",
          "        generatedToken = TokenResponse[access_token] // assign token value",
          "    in generatedToken // end function makeToken",
          "    , ",
          "    // invoke said function",
          "    myToken = makeToken(",
          "                        #\"HaloITSM-ResourceURL\"",
          "                        , #\"HaloITSM-ClientID\"",
          "                        , #\"HaloITSM-Secret\"",
          "                    ) // end makeToken",
          "    , ",
          "    // invoke function on page1 to get ticketCount for pagination",
          "    firstPage = Json.Document(",
          "            Web.Contents(",
          "                #\"HaloITSM-ResourceURL\"",
          "                , [",
          "                    RelativePath = \"Tickets?pageinate=true&page_size=\" & Text.From(#\"pageSize\") & \"&page_no=\" & Text.From(1) // use page 1 to access how many records there will be",
          "                    , Headers = [",
          "                        Authorization = \"Bearer \" &  myToken",
          "                    ]",
          "                ]",
          "            ) // end webcontents",
          "        ),",
          "    pageList = {1..Number.RoundUp(@firstPage[record_count] / pageSize)},",
          "    // a function which asks for one page of data",
          "    getPage = let getPages = (pageNumber) => ",
          "        Json.Document(",
          "            Web.Contents(",
          "                #\"HaloITSM-ResourceURL\"",
          "                , [",
          "                    RelativePath = \"Tickets?pageinate=true&page_size=\" & Text.From(#\"pageSize\") & \"&page_no=\" & Text.From(pageNumber) //pageNumber",
          "                    , Headers = [",
          "                        Authorization = \"Bearer \" &  myToken",
          "                    ]",
          "                ]",
          "            ) // end webcontents",
          "        )[tickets] // get part of json containing ticket list",
          "    in getPages // end function getPage",
          "    , ",
          "    #\"Converted page list to Table\" = Table.FromList(pageList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "    #\"Invoked getPage\" = Table.AddColumn(#\"Converted page list to Table\", \"GetPage\", each getPage(Text.From([Column1]))),",
          "    #\"Expanded getPage list\" = Table.ExpandListColumn(#\"Invoked getPage\", \"GetPage\"),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Expanded getPage list\",{\"GetPage\"}), ",
          "    #\"Expanded getPage Record\" = Table.ExpandRecordColumn(#\"Removed Other Columns\", \"GetPage\", {\"id\", \"dateoccurred\", \"summary\", \"details\", \"status_id\", \"tickettype_id\", \"sla_id\", \"priority_id\", \"client_id\", \"client_name\", \"site_id\", \"site_name\", \"user_id\", \"user_name\", \"team\", \"agent_id\", \"category_1\", \"category_2\", \"category_3\", \"category_4\", \"estimate\", \"estimatedays\", \"parent_id\", \"child_count\", \"attachment_count\", \"flagged\", \"read\", \"enduserstatus\", \"onhold\", \"respondbydate\", \"fixbydate\", \"dateassigned\", \"excludefromsla\", \"slaholdtime\", \"site_timezone\", \"lastactiondate\", \"organisation_id\", \"department_id\", \"reportedby\", \"user_email\", \"emailtolist\", \"emailtolistsupplier\", \"emailcclist\", \"emailcclistsupplier\", \"matched_kb_id\", \"product_id\", \"release_id\", \"release2_id\", \"release3_id\", \"lastincomingemail\", \"inventory_number\", \"workflow_id\", \"workflow_step\", \"hasbeenclosed\", \"is_vip\", \"isimportantcontact\", \"inactive\", \"impact\", \"urgency\", \"startdate\", \"starttime\", \"starttimeslot\", \"targetdate\", \"targettime\", \"targettimeslot\", \"deadlinedate\", \"oppcompanyname\", \"oppvalueadjusted\", \"cost\", \"quantity\", \"projecttimebudget\", \"projectmoneybudget\", \"projecttimeactual\", \"projectmoneyactual\", \"userdef1\", \"userdef2\", \"userdef3\", \"userdef4\", \"userdef5\", \"source\", \"release_important\", \"releasenotegroup_id\", \"third_party_id\", \"third_party_id_string\", \"supplier_status\", \"appointment_type\", \"section_timezone\", \"projectinternaltask\", \"impactlevel\", \"use\", \"maximumRestrictedPriority\", \"idsummary\", \"ticketage\", \"useful_count\", \"notuseful_count\", \"itil_requesttype_id\", \"closed_in_integration_system\", \"approval_status\"}, {\"id\", \"dateoccurred\", \"summary\", \"details\", \"status_id\", \"tickettype_id\", \"sla_id\", \"priority_id\", \"client_id\", \"client_name\", \"site_id\", \"site_name\", \"user_id\", \"user_name\", \"team\", \"agent_id\", \"category_1\", \"category_2\", \"category_3\", \"category_4\", \"estimate\", \"estimatedays\", \"parent_id\", \"child_count\", \"attachment_count\", \"flagged\", \"read\", \"enduserstatus\", \"onhold\", \"respondbydate\", \"fixbydate\", \"dateassigned\", \"excludefromsla\", \"slaholdtime\", \"site_timezone\", \"lastactiondate\", \"organisation_id\", \"department_id\", \"reportedby\", \"user_email\", \"emailtolist\", \"emailtolistsupplier\", \"emailcclist\", \"emailcclistsupplier\", \"matched_kb_id\", \"product_id\", \"release_id\", \"release2_id\", \"release3_id\", \"lastincomingemail\", \"inventory_number\", \"workflow_id\", \"workflow_step\", \"hasbeenclosed\", \"is_vip\", \"isimportantcontact\", \"inactive\", \"impact\", \"urgency\", \"startdate\", \"starttime\", \"starttimeslot\", \"targetdate\", \"targettime\", \"targettimeslot\", \"deadlinedate\", \"oppcompanyname\", \"oppvalueadjusted\", \"cost\", \"quantity\", \"projecttimebudget\", \"projectmoneybudget\", \"projecttimeactual\", \"projectmoneyactual\", \"userdef1\", \"userdef2\", \"userdef3\", \"userdef4\", \"userdef5\", \"source\", \"release_important\", \"releasenotegroup_id\", \"third_party_id\", \"third_party_id_string\", \"supplier_status\", \"appointment_type\", \"section_timezone\", \"projectinternaltask\", \"impactlevel\", \"use\", \"maximumRestrictedPriority\", \"idsummary\", \"ticketage\", \"useful_count\", \"notuseful_count\", \"itil_requesttype_id\", \"closed_in_integration_system\", \"approval_status\"})",
          "in",
          "    #\"Expanded getPage Record\""
        ],
        "kind": "m",
        "lineageTag": "140fddb4-e4ca-400f-9c5c-1a22e2c25a05",
        "queryGroup": "01 API returns\\01-02 Paginated queries"
      },
      {
        "name": "Users Raw",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
          "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
          "        loginURL = #\"HaloITSM-AuthURL\",",
          "        TokenUri = \"/token\", // which domain is this a token for",
          "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
          "        TokenResponse = Json.Document(",
          "            Web.Contents(loginURL",
          "\t\t\t    , [RelativePath = TokenUri",
          "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
          "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
          "\t\t\t    ]",
          "            ) // end web contents",
          "        ), // end json",
          "        generatedToken = TokenResponse[access_token] // assign token value",
          "    in generatedToken, // end function makeToken",
          "    // invoke said function",
          "    myToken = makeToken(",
          "                        #\"HaloITSM-ResourceURL\"",
          "                        , #\"HaloITSM-ClientID\"",
          "                        , #\"HaloITSM-Secret\"",
          "                    ) // end makeToken",
          "    , ",
          "    // invoke function on page1 to get userCount for pagination",
          "    firstPage = Json.Document(",
          "        Web.Contents(",
          "            #\"HaloITSM-ResourceURL\"",
          "            , [",
          "                RelativePath = \"Users?pageinate=true&page_size=\" & Text.From(#\"pageSize\") & \"&page_no=1\"",
          "                , Headers = [",
          "                    Authorization = \"Bearer \" &  myToken",
          "                ]",
          "            ]",
          "        )",
          "    ), ",
          "    pageList = {1..Number.RoundUp(@firstPage[record_count] / pageSize)},",
          "     // a function which asks for one page of data",
          "    getPage = let getPages = (pageNumber) => ",
          "        Json.Document(",
          "            Web.Contents(",
          "                #\"HaloITSM-ResourceURL\"",
          "                , [",
          "                    RelativePath = \"Users?pageinate=true&page_size=\" & Text.From(#\"pageSize\") & \"&page_no=\" & Text.From(pageNumber) //pageNumber",
          "                    , Headers = [",
          "                        Authorization = \"Bearer \" &  myToken",
          "                    ]",
          "                ]",
          "            ) // end webcontents",
          "        )[users] // get part of json containing ticket list",
          "    in getPages, // end function getPage",
          "    #\"Converted pageList to Table\" = Table.FromList(pageList, Splitter.SplitByNothing(), null, null, ExtraValues.Error), ",
          "    #\"Invoked getPage\" = Table.AddColumn(#\"Converted pageList to Table\", \"GetPage\", each getPage(Text.From([Column1]))),",
          "    #\"Expanded GetPage List\" = Table.ExpandListColumn(#\"Invoked getPage\", \"GetPage\"),",
          "    #\"Removed keep only Records\" = Table.SelectColumns(#\"Expanded GetPage List\",{\"GetPage\"}), ",
          "    #\"Expanded GetPage Records\" = Table.ExpandRecordColumn(#\"Removed keep only Records\", \"GetPage\", {\"id\", \"name\", \"site_id\", \"site_name\", \"client_name\", \"firstname\", \"surname\", \"initials\", \"emailaddress\", \"phonenumber_preferred\", \"sitephonenumber\", \"phonenumber\", \"telpref\", \"activedirectory_dn\", \"login\", \"inactive\", \"colour\", \"isimportantcontact\", \"other1\", \"other2\", \"neversendemails\", \"priority_id\", \"linked_agent_id\", \"isserviceaccount\", \"isimportantcontact2\", \"connectwiseid\", \"autotaskid\", \"messagegroup_id\", \"use\", \"client_id\"}, {\"id\", \"name\", \"site_id\", \"site_name\", \"client_name\", \"firstname\", \"surname\", \"initials\", \"emailaddress\", \"phonenumber_preferred\", \"sitephonenumber\", \"phonenumber\", \"telpref\", \"activedirectory_dn\", \"login\", \"inactive\", \"colour\", \"isimportantcontact\", \"other1\", \"other2\", \"neversendemails\", \"priority_id\", \"linked_agent_id\", \"isserviceaccount\", \"isimportantcontact2\", \"connectwiseid\", \"autotaskid\", \"messagegroup_id\", \"use\", \"client_id\"})",
          "in",
          "    #\"Expanded GetPage Records\""
        ],
        "kind": "m",
        "lineageTag": "b006c860-997b-47c6-9742-2c2667fb2979",
        "queryGroup": "01 API returns\\01-02 Paginated queries"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "00 Utilities"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "00 Utilities\\00-00 Params"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "00 Utilities\\00-01 Auth Function"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "01 API returns"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "03 Report Tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ],
        "folder": "99 Testing"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "01 API returns\\01-00 SingleQuery"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "02 Mapping tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "01 API returns\\01-02 Paginated queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "01 API returns\\01-01 Staging Queries"
      }
    ],
    "relationships": [
      {
        "name": "3894d2d1-006d-4f7b-9727-b6cc019a0375",
        "fromColumn": "tickettype_id",
        "fromTable": "Tickets",
        "toColumn": "ticket type id",
        "toTable": "TicketTypes"
      },
      {
        "name": "fcb24200-3c2e-438a-ad77-99afa77b1f87",
        "fromColumn": "user_id",
        "fromTable": "Tickets",
        "toColumn": "user id",
        "toTable": "Users"
      },
      {
        "name": "70e4bc1f-62c0-42cc-9833-c0d6357b459e",
        "fromColumn": "client_id",
        "fromTable": "Users",
        "toColumn": "client id",
        "toTable": "Clients"
      },
      {
        "name": "a8116590-0e0e-41c9-b6ed-bd885faa26d5",
        "fromColumn": "client_id",
        "fromTable": "Sites",
        "toColumn": "client id",
        "toTable": "Clients"
      },
      {
        "name": "5531123c-d30e-4367-aa6b-ace28699166d",
        "fromColumn": "agent_id",
        "fromTable": "Tickets",
        "toColumn": "agent id",
        "toTable": "Agents"
      },
      {
        "name": "861ab5ea-13c5-4110-994b-6f44244faf26",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "agent id",
        "fromTable": "Agent teams",
        "isActive": false,
        "toColumn": "agent id",
        "toTable": "Agents"
      },
      {
        "name": "7b61e748-a971-4f4e-864c-8c9d77fac6ec",
        "fromColumn": "team_id",
        "fromTable": "Agent teams",
        "isActive": false,
        "toColumn": "team_id",
        "toTable": "Teams"
      },
      {
        "name": "1e7c6081-ffd2-43e6-8e1d-93196de0f1ac",
        "fromColumn": "status_id",
        "fromTable": "Tickets",
        "toColumn": "status id",
        "toTable": "Statuses"
      },
      {
        "name": "58bee739-cfee-4146-9a1a-d5ddc0fd969e",
        "fromColumn": "linked_agent_id",
        "fromTable": "Users",
        "isActive": false,
        "toColumn": "agent id",
        "toTable": "Agents"
      },
      {
        "name": "01943fcc-e835-4de6-bc74-01123e4dfe67",
        "fromColumn": "site_id",
        "fromTable": "Users",
        "isActive": false,
        "toColumn": "site id",
        "toTable": "Sites"
      },
      {
        "name": "8d34ef16-f344-4522-9eba-0abdf6097640",
        "fromColumn": "site_id",
        "fromTable": "Tickets",
        "isActive": false,
        "toColumn": "site id",
        "toTable": "Sites"
      },
      {
        "name": "d523efd8-f496-4d0c-b7fd-8b23e2e73524",
        "fromColumn": "Primary team",
        "fromTable": "Agents",
        "isActive": false,
        "toColumn": "name",
        "toTable": "Teams"
      },
      {
        "name": "1f0cad09-adf6-40b0-b24f-228bf45751f4",
        "fromColumn": "team",
        "fromTable": "Tickets",
        "toColumn": "name",
        "toTable": "Teams"
      },
      {
        "name": "ca279a25-bcfa-4fee-8840-85583af78a26",
        "fromColumn": "Date Created",
        "fromTable": "Tickets",
        "toColumn": "Date",
        "toTable": "DateDimensionBI"
      }
    ],
    "sourceQueryCulture": "en-AU",
    "tables": [
      {
        "name": "TicketTypes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ticket type id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aff29af9-9cb9-407b-904b-1db32b162410",
            "sourceColumn": "ticket type id",
            "summarizeBy": "none"
          },
          {
            "name": "guid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21ded55f-7768-40f0-8ae7-8cb9eda9f11c",
            "sourceColumn": "guid",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "320cf3c5-443e-4239-9c52-1f024bd57705",
            "sourceColumn": "name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cc849e06-7c92-4a41-ba3b-764008565686",
        "partitions": [
          {
            "name": "TicketTypes",
            "mode": "import",
            "queryGroup": "01 API returns\\01-00 SingleQuery",
            "source": {
              "expression": [
                "let",
                "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
                "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
                "        loginURL = #\"HaloITSM-AuthURL\",",
                "        TokenUri = \"/token\", // which domain is this a token for",
                "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
                "        TokenResponse = Json.Document(",
                "            Web.Contents(loginURL",
                "\t\t\t    , [RelativePath = TokenUri",
                "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
                "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
                "\t\t\t    ]",
                "            ) // end web contents",
                "        ), // end json",
                "        generatedToken = TokenResponse[access_token] // assign token value",
                "    in",
                "    generatedToken,",
                "    myToken = makeToken(",
                "                        #\"HaloITSM-ResourceURL\"",
                "                        , #\"HaloITSM-ClientID\"",
                "                        , #\"HaloITSM-Secret\"",
                "                    ) // end makeToken",
                "    , ",
                "    // Ping API for json",
                "    TicketTypesReturn = Json.Document(",
                "        Web.Contents(",
                "            #\"HaloITSM-ResourceURL\"",
                "            , [",
                "                RelativePath = \"TicketType\"",
                "                , Headers = [",
                "                    Authorization = \"Bearer \" ",
                "                    &  myToken",
                "                ]",
                "            ]",
                "        )",
                "    ),",
                "    #\"Converted to Table\" = Table.FromList(TicketTypesReturn, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Expanded Records\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"guid\", \"name\", \"sequence\", \"default_sla\", \"group_id\", \"group_name\", \"jira_issue_type\", \"cancreate\", \"agentscanselect\", \"itilrequesttype\", \"allowattachments\", \"copyattachmentstochild\", \"is_sprint\", \"enduserscanselect\", \"anonymouscanselect\", \"kanbanstatuschoice\", \"kanbanstatuschoice_list\"}, {\"id\", \"guid\", \"name\", \"sequence\", \"default_sla\", \"group_id\", \"group_name\", \"jira_issue_type\", \"cancreate\", \"agentscanselect\", \"itilrequesttype\", \"allowattachments\", \"copyattachmentstochild\", \"is_sprint\", \"enduserscanselect\", \"anonymouscanselect\", \"kanbanstatuschoice\", \"kanbanstatuschoice_list\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Records\",{{\"cancreate\", type logical}, {\"agentscanselect\", type logical}, {\"allowattachments\", type logical}, {\"copyattachmentstochild\", type logical}, {\"is_sprint\", type logical}, {\"enduserscanselect\", type logical}, {\"anonymouscanselect\", type logical}, {\"id\", type text}}),",
                "    #\"Renamed id to ticketID\" = Table.RenameColumns(#\"Changed Type\",{{\"id\", \"ticket type id\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed id to ticketID\",{\"ticket type id\", \"guid\", \"name\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Users",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "user id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce1edcff-440c-4787-8fb8-14b4488b40ac",
            "sourceColumn": "user id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48ef134e-ed65-49db-80d1-9403cef92325",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "site_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ebf491a-3efb-4771-906f-4a2a5348edf5",
            "sourceColumn": "site_id",
            "summarizeBy": "none"
          },
          {
            "name": "site_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b8dd80d-9b8a-4ec5-9688-595fe9347f5d",
            "sourceColumn": "site_name",
            "summarizeBy": "none"
          },
          {
            "name": "client_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b619119f-22e8-4f0e-91c0-2e86746620e8",
            "sourceColumn": "client_name",
            "summarizeBy": "none"
          },
          {
            "name": "firstname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f9f2a72-e1fa-43f2-8f7a-ede5093f2053",
            "sourceColumn": "firstname",
            "summarizeBy": "none"
          },
          {
            "name": "surname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6b8ee96-a25d-43d6-a049-43e559aead14",
            "sourceColumn": "surname",
            "summarizeBy": "none"
          },
          {
            "name": "initials",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d72ab68e-ddbb-42c0-997a-7ac892b70d90",
            "sourceColumn": "initials",
            "summarizeBy": "none"
          },
          {
            "name": "emailaddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea756dd5-fc57-417d-b680-cd98b9fbebb4",
            "sourceColumn": "emailaddress",
            "summarizeBy": "none"
          },
          {
            "name": "phonenumber_preferred",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9dd18a3-7d6e-4976-9872-52694842cd23",
            "sourceColumn": "phonenumber_preferred",
            "summarizeBy": "none"
          },
          {
            "name": "sitephonenumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fff54bc7-dbaa-4e93-ade3-3b9c681c10ef",
            "sourceColumn": "sitephonenumber",
            "summarizeBy": "none"
          },
          {
            "name": "phonenumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbb410d3-d854-4739-a295-b4040a4ee230",
            "sourceColumn": "phonenumber",
            "summarizeBy": "none"
          },
          {
            "name": "activedirectory_dn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f73affd0-00e1-4f8d-a484-75d723e733b9",
            "sourceColumn": "activedirectory_dn",
            "summarizeBy": "none"
          },
          {
            "name": "login",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5a64c3e-cf74-4a41-a9ea-06c3ff610d83",
            "sourceColumn": "login",
            "summarizeBy": "none"
          },
          {
            "name": "inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "cf79d8e3-d260-4ab4-87fe-28fd9819ecf7",
            "sourceColumn": "inactive",
            "summarizeBy": "none"
          },
          {
            "name": "colour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c9fb753-6df1-4eee-935d-a737ad7e3c93",
            "sourceColumn": "colour",
            "summarizeBy": "none"
          },
          {
            "name": "Role level 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be6d2d5f-4d11-4640-8abc-5740f30507f7",
            "sourceColumn": "Role level 1",
            "summarizeBy": "none"
          },
          {
            "name": "Role level 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97345932-facf-45f3-9492-bc20ce171c91",
            "sourceColumn": "Role level 2",
            "summarizeBy": "none"
          },
          {
            "name": "linked_agent_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7bfabb06-d320-48a0-b449-7cfd013506b7",
            "sourceColumn": "linked_agent_id",
            "summarizeBy": "none"
          },
          {
            "name": "client_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23a39e0b-1a22-40ca-8d3e-492ada809f9e",
            "sourceColumn": "client_id",
            "summarizeBy": "none"
          },
          {
            "name": "IsGeneralUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f0b3bcb3-27c9-4494-8d1b-7e09569f2a39",
            "sourceColumn": "IsGeneralUser",
            "summarizeBy": "none"
          }
        ],
        "description": "may need pagination",
        "lineageTag": "fb7d9636-1131-4678-a273-60bf93e39487",
        "partitions": [
          {
            "name": "Users",
            "mode": "import",
            "queryGroup": "03 Report Tables",
            "source": {
              "expression": [
                "// Users",
                "let    ",
                "    Source = #\"Users Raw\", ",
                "    #\"Renamed id to UserId\" = Table.RenameColumns(Source,{{\"id\", \"user id\"}}),",
                "    #\"Changed types to T|F\" = Table.TransformColumnTypes(#\"Renamed id to UserId\",{{\"inactive\", type logical}, {\"isimportantcontact\", type logical}, {\"neversendemails\", type logical}, {\"isserviceaccount\", type logical}, {\"isimportantcontact2\", type logical}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed types to T|F\",{\"user id\", \"name\", \"site_id\", \"site_name\", \"client_id\", \"client_name\", \"firstname\", \"surname\", \"initials\", \"emailaddress\", \"phonenumber_preferred\", \"sitephonenumber\", \"phonenumber\", \"activedirectory_dn\", \"login\", \"inactive\", \"colour\", \"other1\", \"other2\", \"linked_agent_id\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"other1\", \"Role level 1\"}, {\"other2\", \"Role level 2\"}}),",
                "    #\"Replaced Unknown w/ blank\" = Table.ReplaceValue(#\"Renamed Columns\",\"Unknown\",\"\",Replacer.ReplaceText,{\"phonenumber_preferred\", \"sitephonenumber\", \"phonenumber\"}),",
                "    #\"Replaced blanks w/ null\" = Table.ReplaceValue(#\"Replaced Unknown w/ blank\",\"\",null,Replacer.ReplaceValue,{\"user id\", \"name\", \"site_id\", \"site_name\", \"client_id\", \"client_name\", \"firstname\", \"surname\", \"initials\", \"emailaddress\", \"phonenumber_preferred\", \"sitephonenumber\", \"phonenumber\", \"activedirectory_dn\", \"login\", \"inactive\", \"colour\", \"Role level 1\", \"Role level 2\", \"linked_agent_id\"}),",
                "    #\"Added is General User\" = Table.AddColumn(#\"Replaced blanks w/ null\", \"IsGeneralUser\", each [name] = \"General User\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added is General User\",{{\"IsGeneralUser\", type logical}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Clients",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "client id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92d9f932-49b0-4b2f-92d5-9bbde53c7ceb",
            "sourceColumn": "client id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "968125ef-aa2b-4b41-b9cd-0b3fca243534",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "24e0a5d9-bc91-481e-83d9-37949ae8a583",
            "sourceColumn": "inactive",
            "summarizeBy": "none"
          },
          {
            "name": "colour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f0c624b-658c-43f0-9392-44e8a2f7a46e",
            "sourceColumn": "colour",
            "summarizeBy": "none"
          },
          {
            "name": "is_vip",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "a41d07a4-93ac-4b23-941a-f85a49fe5a81",
            "sourceColumn": "is_vip",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b80d486c-a37e-430e-ba7c-a856aef2f4ba",
        "partitions": [
          {
            "name": "Clients",
            "mode": "import",
            "queryGroup": "01 API returns\\01-00 SingleQuery",
            "source": {
              "expression": [
                "let",
                "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
                "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
                "        loginURL = #\"HaloITSM-AuthURL\",",
                "        TokenUri = \"/token\", // which domain is this a token for",
                "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
                "        TokenResponse = Json.Document(",
                "            Web.Contents(loginURL",
                "\t\t\t    , [RelativePath = TokenUri",
                "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
                "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
                "\t\t\t    ]",
                "            ) // end web contents",
                "        ), // end json",
                "        generatedToken = TokenResponse[access_token] // assign token value",
                "    in",
                "    generatedToken,",
                "    myToken = makeToken(",
                "                        #\"HaloITSM-ResourceURL\"",
                "                        , #\"HaloITSM-ClientID\"",
                "                        , #\"HaloITSM-Secret\"",
                "                    ) // end makeToken",
                "    , ",
                "    // Ping API for json",
                "    #\"Clients API return\" = Json.Document(",
                "        Web.Contents(",
                "            #\"HaloITSM-ResourceURL\"",
                "            , [",
                "                RelativePath = \"Client\"",
                "                , Headers = [",
                "                    Authorization = \"Bearer \" ",
                "                    &  myToken",
                "                ]",
                "            ]",
                "        )",
                "    )[clients],",
                "    #\"Converted to Table\" = Table.FromList(#\"Clients API return\", Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Expanded Records\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"name\", \"toplevel_id\", \"toplevel_name\", \"inactive\", \"colour\", \"confirmemail\", \"actionemail\", \"clearemail\", \"messagegroup_id\", \"from_address_override\", \"mailbox_override\", \"default_mailbox_id\", \"item_tax_code\", \"service_tax_code\", \"prepay_tax_code\", \"contract_tax_code\", \"pritech\", \"sectech\", \"accountmanagertech\", \"use\", \"xero_tenant_id\", \"overridepdftemplateinvoice\", \"kashflow_tenant_id\", \"client_to_invoice\", \"invoiceduedaysextraclient\", \"itglue_id\", \"clientcurrency\", \"sentinel_subscription_id\", \"sentinel_workspace_name\", \"sentinel_resource_group_name\", \"default_currency_code\", \"client_to_invoice_recurring\", \"dbc_company_id\", \"stopped\", \"customertype\", \"sentinel_default_user_override\", \"ref\", \"ticket_invoices_for_each_site\", \"is_vip\", \"taxable\", \"percentage_to_survey\", \"notes\", \"qbo_company_id\", \"servicenow_validated\", \"jira_validated\"}, {\"id\", \"name\", \"toplevel_id\", \"toplevel_name\", \"inactive\", \"colour\", \"confirmemail\", \"actionemail\", \"clearemail\", \"messagegroup_id\", \"from_address_override\", \"mailbox_override\", \"default_mailbox_id\", \"item_tax_code\", \"service_tax_code\", \"prepay_tax_code\", \"contract_tax_code\", \"pritech\", \"sectech\", \"accountmanagertech\", \"use\", \"xero_tenant_id\", \"overridepdftemplateinvoice\", \"kashflow_tenant_id\", \"client_to_invoice\", \"invoiceduedaysextraclient\", \"itglue_id\", \"clientcurrency\", \"sentinel_subscription_id\", \"sentinel_workspace_name\", \"sentinel_resource_group_name\", \"default_currency_code\", \"client_to_invoice_recurring\", \"dbc_company_id\", \"stopped\", \"customertype\", \"sentinel_default_user_override\", \"ref\", \"ticket_invoices_for_each_site\", \"is_vip\", \"taxable\", \"percentage_to_survey\", \"notes\", \"qbo_company_id\", \"servicenow_validated\", \"jira_validated\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Records\",{{\"inactive\", type logical}, {\"ticket_invoices_for_each_site\", type logical}, {\"is_vip\", type logical}, {\"taxable\", type logical}, {\"servicenow_validated\", type logical}, {\"jira_validated\", type logical}, {\"id\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"id\", \"client id\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed Columns\",{\"client id\", \"name\", \"inactive\", \"colour\", \"is_vip\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sites",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "site id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edcce832-3d07-48bb-b9ba-b23c14c4cccf",
            "sourceColumn": "site id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6863c085-3c6e-4179-a0e3-b39c7fa4e061",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "client_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1909cc10-3d75-4714-9f66-4a7634c72e11",
            "sourceColumn": "client_id",
            "summarizeBy": "none"
          },
          {
            "name": "client_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e936a5df-96c8-4816-a9e7-814b729d0a86",
            "sourceColumn": "client_name",
            "summarizeBy": "none"
          },
          {
            "name": "clientsite_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15fa9e55-24b4-45f7-9091-137dd8e07aea",
            "sourceColumn": "clientsite_name",
            "summarizeBy": "none"
          },
          {
            "name": "inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "47830df7-423e-4a78-a110-63693df7269a",
            "sourceColumn": "inactive",
            "summarizeBy": "none"
          },
          {
            "name": "phonenumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f12c9c57-4373-45cd-bd61-bd6a3fbc11b6",
            "sourceColumn": "phonenumber",
            "summarizeBy": "none"
          },
          {
            "name": "colour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea57c1e9-0e86-4fb8-a6cb-be9fe77c4027",
            "sourceColumn": "colour",
            "summarizeBy": "none"
          },
          {
            "name": "timezone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b0cd34e-9e1c-4486-8939-c11368abad70",
            "sourceColumn": "timezone",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "00c4dc7c-ef0e-48f7-923c-24ce3c0353f4",
        "partitions": [
          {
            "name": "Sites",
            "mode": "import",
            "queryGroup": "01 API returns\\01-00 SingleQuery",
            "source": {
              "expression": [
                "let",
                "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
                "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
                "        loginURL = #\"HaloITSM-AuthURL\",",
                "        TokenUri = \"/token\", // which domain is this a token for",
                "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
                "        TokenResponse = Json.Document(",
                "            Web.Contents(loginURL",
                "\t\t\t    , [RelativePath = TokenUri",
                "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
                "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
                "\t\t\t    ]",
                "            ) // end web contents",
                "        ), // end json",
                "        generatedToken = TokenResponse[access_token] // assign token value",
                "    in",
                "    generatedToken,",
                "    myToken = makeToken(",
                "                        #\"HaloITSM-ResourceURL\"",
                "                        , #\"HaloITSM-ClientID\"",
                "                        , #\"HaloITSM-Secret\"",
                "                    ) // end makeToken",
                "    , ",
                "    // Ping API for json",
                "    #\"Sites API return\" = Json.Document(",
                "        Web.Contents(",
                "            #\"HaloITSM-ResourceURL\"",
                "            , [",
                "                RelativePath = \"Site\"",
                "                , Headers = [",
                "                    Authorization = \"Bearer \" ",
                "                    &  myToken",
                "                ]",
                "            ]",
                "        )",
                "    )[sites],",
                "    #\"Converted to Table\" = Table.FromList(#\"Sites API return\", Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Expanded Records\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"name\", \"client_id\", \"client_name\", \"clientsite_name\", \"inactive\", \"sla_id\", \"phonenumber\", \"colour\", \"timezone\", \"invoice_address_isdelivery\", \"isstocklocation\", \"messagegroup_id\", \"use\"}, {\"id\", \"name\", \"client_id\", \"client_name\", \"clientsite_name\", \"inactive\", \"sla_id\", \"phonenumber\", \"colour\", \"timezone\", \"invoice_address_isdelivery\", \"isstocklocation\", \"messagegroup_id\", \"use\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Records\",{{\"inactive\", type logical}, {\"invoice_address_isdelivery\", type logical}, {\"isstocklocation\", type logical}, {\"id\", type text}, {\"client_id\", type text}, {\"phonenumber\", type text}}),",
                "    #\"Renamed id to site ID\" = Table.RenameColumns(#\"Changed Type\",{{\"id\", \"site id\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed id to site ID\",{\"site id\", \"name\", \"client_id\", \"client_name\", \"clientsite_name\", \"inactive\", \"phonenumber\", \"colour\", \"timezone\"}),",
                "    #\"Replaced Unknown w/ blank\" = Table.ReplaceValue(#\"Removed Other Columns\",\"Unknown\",\"\",Replacer.ReplaceText,{\"phonenumber\"}),",
                "    #\"Replaced blank w/ null\" = Table.ReplaceValue(#\"Replaced Unknown w/ blank\",\"\",null,Replacer.ReplaceValue,{\"phonenumber\", \"colour\", \"timezone\"})",
                "in",
                "    #\"Replaced blank w/ null\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Suppliers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "supplier id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6545773e-6d06-48e6-8923-4d9fa49d3f45",
            "sourceColumn": "supplier id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94eb3100-5d6d-474e-9855-f237b4fb1c67",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "logo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a797c90-012f-4901-b567-1693cfb271b5",
            "sourceColumn": "logo",
            "summarizeBy": "none"
          },
          {
            "name": "contact_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "508c28f9-eacd-4ba2-be6a-fd216fa488c6",
            "sourceColumn": "contact_name",
            "summarizeBy": "none"
          },
          {
            "name": "email_address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6c3c62f-7693-42cb-8627-e7788044538b",
            "sourceColumn": "email_address",
            "summarizeBy": "none"
          },
          {
            "name": "support_email_address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01dbedf1-379c-48ba-97d5-75eff00bed6f",
            "sourceColumn": "support_email_address",
            "summarizeBy": "none"
          },
          {
            "name": "phone_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5344345b-d636-405c-9668-d630d82e592f",
            "sourceColumn": "phone_number",
            "summarizeBy": "none"
          },
          {
            "name": "inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "205c1cf8-4e4b-483d-9b30-33dfadbac11f",
            "sourceColumn": "inactive",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "371e79b1-170f-4873-a00d-9c4428a071a4",
        "partitions": [
          {
            "name": "Suppliers",
            "mode": "import",
            "queryGroup": "01 API returns\\01-00 SingleQuery",
            "source": {
              "expression": [
                "let",
                "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
                "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
                "        loginURL = #\"HaloITSM-AuthURL\",",
                "        TokenUri = \"/token\", // which domain is this a token for",
                "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
                "        TokenResponse = Json.Document(",
                "            Web.Contents(loginURL",
                "\t\t\t    , [RelativePath = TokenUri",
                "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
                "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
                "\t\t\t    ]",
                "            ) // end web contents",
                "        ), // end json",
                "        generatedToken = TokenResponse[access_token] // assign token value",
                "    in",
                "    generatedToken,",
                "    myToken = makeToken(",
                "                        #\"HaloITSM-ResourceURL\"",
                "                        , #\"HaloITSM-ClientID\"",
                "                        , #\"HaloITSM-Secret\"",
                "                    ) // end makeToken",
                "    , ",
                "    // Ping API for json",
                "    #\"Suppliers API return\" = Json.Document(",
                "        Web.Contents(",
                "            #\"HaloITSM-ResourceURL\"",
                "            , [",
                "                RelativePath = \"Supplier\"",
                "                , Headers = [",
                "                    Authorization = \"Bearer \" ",
                "                    &  myToken",
                "                ]",
                "            ]",
                "        )",
                "    )[suppliers],",
                "    #\"Converted to Table\" = Table.FromList(#\"Suppliers API return\", Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Expanded Records\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"name\", \"logo\", \"toplevel_id\", \"toplevel_name\", \"contact_name\", \"email_address\", \"support_email_address\", \"phone_number\", \"inactive\", \"emailtemplate_id\", \"thirdpartynhdapiurl\", \"contract_count\", \"use\", \"supplier_mailbox_override\", \"supplier_mailbox_address\", \"qbo_company_id\"}, {\"id\", \"name\", \"logo\", \"toplevel_id\", \"toplevel_name\", \"contact_name\", \"email_address\", \"support_email_address\", \"phone_number\", \"inactive\", \"emailtemplate_id\", \"thirdpartynhdapiurl\", \"contract_count\", \"use\", \"supplier_mailbox_override\", \"supplier_mailbox_address\", \"qbo_company_id\"}),",
                "    #\"Renamed id to supplier ID\" = Table.RenameColumns(#\"Expanded Records\",{{\"id\", \"supplier id\"}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Renamed id to supplier ID\",{\"supplier id\", \"name\", \"logo\", \"contact_name\", \"email_address\", \"support_email_address\", \"phone_number\", \"inactive\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Other Columns\",{{\"supplier id\", type text}, {\"inactive\", type logical}}),",
                "    #\"Replaced blanks w/ null\" = Table.ReplaceValue(#\"Changed Type\",\"\",null,Replacer.ReplaceValue,{\"supplier id\", \"name\", \"logo\", \"contact_name\", \"email_address\", \"support_email_address\", \"phone_number\", \"inactive\"})",
                "in",
                "    #\"Replaced blanks w/ null\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tickets",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ticket id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cea39e1f-08f8-4c16-bf21-ece26c8a5420",
            "sourceColumn": "ticket id",
            "summarizeBy": "none"
          },
          {
            "name": "dateoccurred",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "11d8ac00-1665-4f9d-aae5-7afec56c438d",
            "sourceColumn": "dateoccurred",
            "summarizeBy": "none"
          },
          {
            "name": "summary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62357112-8ef0-4c2f-a283-2f678a6edea0",
            "sourceColumn": "summary",
            "summarizeBy": "none"
          },
          {
            "name": "details",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a986520-f2dc-4392-9cf3-f1d32d75bd4d",
            "sourceColumn": "details",
            "summarizeBy": "none"
          },
          {
            "name": "status_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb7d6979-0993-4443-87f3-f241f9f1aec2",
            "sourceColumn": "status_id",
            "summarizeBy": "none"
          },
          {
            "name": "tickettype_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9730b70d-bf38-480f-acaa-cd07e860ca3b",
            "sourceColumn": "tickettype_id",
            "summarizeBy": "none"
          },
          {
            "name": "sla_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a56976d1-14dd-4ae0-9a93-605a1e8e94a3",
            "sourceColumn": "sla_id",
            "summarizeBy": "none"
          },
          {
            "name": "priority_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2489a6f-1f41-49a6-acff-4ee656da523b",
            "sourceColumn": "priority_id",
            "summarizeBy": "none"
          },
          {
            "name": "client_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "daebd041-265f-4761-b8f0-6b8b9a137756",
            "sourceColumn": "client_id",
            "summarizeBy": "none"
          },
          {
            "name": "client_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d1b061a-fe91-4e5c-ac2a-8bf217a7eae9",
            "sourceColumn": "client_name",
            "summarizeBy": "none"
          },
          {
            "name": "site_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "765a553b-3773-4e05-b1e9-4131d9ab804a",
            "sourceColumn": "site_id",
            "summarizeBy": "none"
          },
          {
            "name": "site_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d5b5a94-9dae-495c-abbc-6b5e571d46a6",
            "sourceColumn": "site_name",
            "summarizeBy": "none"
          },
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15f5576d-e449-4c71-a96e-dcf67c5adc62",
            "sourceColumn": "user_id",
            "summarizeBy": "none"
          },
          {
            "name": "user_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d720e9c-a4be-4fb1-ab82-d8e58c79d129",
            "sourceColumn": "user_name",
            "summarizeBy": "none"
          },
          {
            "name": "team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8de3a7a8-e826-440c-86be-7e2f274e5597",
            "sourceColumn": "team",
            "summarizeBy": "none"
          },
          {
            "name": "agent_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2eb3ae64-a6c9-406a-9f7b-c6522b56cbc7",
            "sourceColumn": "agent_id",
            "summarizeBy": "none"
          },
          {
            "name": "category_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd49a5e5-bc6a-424e-9693-2bdc199fbc75",
            "sourceColumn": "category_1",
            "summarizeBy": "none"
          },
          {
            "name": "estimate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "875ef6c8-d4ed-44e9-9acd-7fed187d46db",
            "sourceColumn": "estimate",
            "summarizeBy": "none"
          },
          {
            "name": "estimatedays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0e36fb1-3e56-42ee-a332-98776d5092ec",
            "sourceColumn": "estimatedays",
            "summarizeBy": "none"
          },
          {
            "name": "parent_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b844cfe-3d70-4881-829d-8d747c558ae4",
            "sourceColumn": "parent_id",
            "summarizeBy": "none"
          },
          {
            "name": "child_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5600fc3e-6af9-4529-98b2-dbd3285dfe60",
            "sourceColumn": "child_count",
            "summarizeBy": "none"
          },
          {
            "name": "attachment_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8347bf5-819e-4edc-a049-2be77df44060",
            "sourceColumn": "attachment_count",
            "summarizeBy": "none"
          },
          {
            "name": "flagged",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c70091f-904a-4968-aeb2-9fbbe8058ee4",
            "sourceColumn": "flagged",
            "summarizeBy": "none"
          },
          {
            "name": "read",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd777491-ebda-454e-9b0b-a1a59b392ce1",
            "sourceColumn": "read",
            "summarizeBy": "none"
          },
          {
            "name": "enduserstatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "853b4e74-56c0-48dc-9a2b-433719c1d838",
            "sourceColumn": "enduserstatus",
            "summarizeBy": "none"
          },
          {
            "name": "onhold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3a7db0d2-1bd2-47d7-b1c4-762cab1fe395",
            "sourceColumn": "onhold",
            "summarizeBy": "none"
          },
          {
            "name": "dateassigned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5369ef50-d05e-4845-976b-221148a46168",
            "sourceColumn": "dateassigned",
            "summarizeBy": "none"
          },
          {
            "name": "excludefromsla",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0cd273fa-8837-4533-aa15-3ede882fd932",
            "sourceColumn": "excludefromsla",
            "summarizeBy": "none"
          },
          {
            "name": "slaholdtime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac8091bf-4d63-4718-9276-14c219efb02c",
            "sourceColumn": "slaholdtime",
            "summarizeBy": "none"
          },
          {
            "name": "site_timezone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86c04690-5f8e-48b3-ad71-d81e91f6b7d3",
            "sourceColumn": "site_timezone",
            "summarizeBy": "none"
          },
          {
            "name": "lastactiondate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c5a9eff9-1af0-483a-9e0a-dae40e9b7beb",
            "sourceColumn": "lastactiondate",
            "summarizeBy": "none"
          },
          {
            "name": "organisation_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95c301c3-0a79-41c3-8324-14917ecffc5b",
            "sourceColumn": "organisation_id",
            "summarizeBy": "none"
          },
          {
            "name": "department_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75b6a50c-0fec-4903-a9fd-dfbd01dfd781",
            "sourceColumn": "department_id",
            "summarizeBy": "none"
          },
          {
            "name": "reportedby",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0120fb93-c991-4151-9842-8d48664e83b6",
            "sourceColumn": "reportedby",
            "summarizeBy": "none"
          },
          {
            "name": "user_email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc580cbf-6622-456b-8f70-137d233cc753",
            "sourceColumn": "user_email",
            "summarizeBy": "none"
          },
          {
            "name": "emailtolist",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca9fffd5-576d-47df-8895-590d35c2b8c3",
            "sourceColumn": "emailtolist",
            "summarizeBy": "none"
          },
          {
            "name": "emailtolistsupplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "520bc4e4-9ceb-4a93-85ce-f51d230ef9a3",
            "sourceColumn": "emailtolistsupplier",
            "summarizeBy": "none"
          },
          {
            "name": "emailcclist",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "623d9933-d4cd-4282-822e-a8761a4135fa",
            "sourceColumn": "emailcclist",
            "summarizeBy": "none"
          },
          {
            "name": "emailcclistsupplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9c3f0c0-a8ea-4a06-bd4e-4e1a4d8167f5",
            "sourceColumn": "emailcclistsupplier",
            "summarizeBy": "none"
          },
          {
            "name": "matched_kb_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b104e1a-6f93-45f1-bda2-827df945069b",
            "sourceColumn": "matched_kb_id",
            "summarizeBy": "none"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c97768ae-6d27-4213-8de4-e647614472ee",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "release_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0954082d-3277-40cd-8f3a-3f5e2522c8ea",
            "sourceColumn": "release_id",
            "summarizeBy": "none"
          },
          {
            "name": "release2_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2e74612-2a79-42ba-873b-9c1977225d5a",
            "sourceColumn": "release2_id",
            "summarizeBy": "none"
          },
          {
            "name": "release3_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc25311e-09da-4106-8a9a-c95c5e3ea68f",
            "sourceColumn": "release3_id",
            "summarizeBy": "none"
          },
          {
            "name": "inventory_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03491951-0cdf-4624-b924-b2021d8f1825",
            "sourceColumn": "inventory_number",
            "summarizeBy": "none"
          },
          {
            "name": "workflow_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efd19ccf-e6ff-4b91-9dfe-35de32ccd7c4",
            "sourceColumn": "workflow_id",
            "summarizeBy": "none"
          },
          {
            "name": "workflow_step",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65783e75-8931-41ee-962c-4ca6e6f84606",
            "sourceColumn": "workflow_step",
            "summarizeBy": "none"
          },
          {
            "name": "hasbeenclosed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c7b1c6bc-0c10-4590-a576-ff418d4d3dc9",
            "sourceColumn": "hasbeenclosed",
            "summarizeBy": "none"
          },
          {
            "name": "is_vip",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0c0e52ff-6b3a-4115-be26-713e2c8bc9c1",
            "sourceColumn": "is_vip",
            "summarizeBy": "none"
          },
          {
            "name": "isimportantcontact",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "de66c957-ad6a-46af-b71f-00a2b175fbec",
            "sourceColumn": "isimportantcontact",
            "summarizeBy": "none"
          },
          {
            "name": "inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "47b10b2b-081e-487b-9406-acd80ea4b442",
            "sourceColumn": "inactive",
            "summarizeBy": "none"
          },
          {
            "name": "impact",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdc539c6-4c44-4808-ac86-52f24767646f",
            "sourceColumn": "impact",
            "summarizeBy": "none"
          },
          {
            "name": "urgency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5753f2ab-74b3-4910-9c3e-f355441e1c58",
            "sourceColumn": "urgency",
            "summarizeBy": "none"
          },
          {
            "name": "oppcompanyname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e54b19a-23ac-426e-8554-cfaebe330520",
            "sourceColumn": "oppcompanyname",
            "summarizeBy": "none"
          },
          {
            "name": "oppvalueadjusted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58aa2540-5ed0-4abe-b7e7-811a324a3fcb",
            "sourceColumn": "oppvalueadjusted",
            "summarizeBy": "none"
          },
          {
            "name": "cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5edbe630-d60b-4d82-bf27-9c83cde0cdcc",
            "sourceColumn": "cost",
            "summarizeBy": "none"
          },
          {
            "name": "quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e62695c4-2831-4a73-91a1-8ecc6e2ec1a3",
            "sourceColumn": "quantity",
            "summarizeBy": "none"
          },
          {
            "name": "projecttimebudget",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a509498d-9f65-4330-9e8c-3d1bf6b458fd",
            "sourceColumn": "projecttimebudget",
            "summarizeBy": "none"
          },
          {
            "name": "projectmoneybudget",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17364ece-a815-4ef2-9574-356d8a0c46c0",
            "sourceColumn": "projectmoneybudget",
            "summarizeBy": "none"
          },
          {
            "name": "projecttimeactual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1022e2c-8789-43dc-84ba-683eccea10bd",
            "sourceColumn": "projecttimeactual",
            "summarizeBy": "none"
          },
          {
            "name": "projectmoneyactual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d50f3c22-eefa-40da-966e-dbff973bae6a",
            "sourceColumn": "projectmoneyactual",
            "summarizeBy": "none"
          },
          {
            "name": "userdef1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65a7cc29-12ef-45d1-9b26-7b0945cc6687",
            "sourceColumn": "userdef1",
            "summarizeBy": "none"
          },
          {
            "name": "userdef2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45dc5965-0405-4f2e-919d-cf59b674011a",
            "sourceColumn": "userdef2",
            "summarizeBy": "none"
          },
          {
            "name": "userdef3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1eda894c-ebdd-43ff-83a4-bf433a175909",
            "sourceColumn": "userdef3",
            "summarizeBy": "none"
          },
          {
            "name": "userdef4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "563d80b2-3068-4994-8ca0-5cc92b791aa7",
            "sourceColumn": "userdef4",
            "summarizeBy": "none"
          },
          {
            "name": "userdef5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65fa21df-14ca-4d91-9e4f-c351c22dd29b",
            "sourceColumn": "userdef5",
            "summarizeBy": "none"
          },
          {
            "name": "source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e00d30c6-bdff-4641-a6cc-d248b04c5d98",
            "sourceColumn": "source",
            "summarizeBy": "none"
          },
          {
            "name": "release_important",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "fdcfb329-597c-4667-a8f6-7ad487b36ea7",
            "sourceColumn": "release_important",
            "summarizeBy": "none"
          },
          {
            "name": "releasenotegroup_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95b1130e-c31b-4377-b763-336a97e43cd8",
            "sourceColumn": "releasenotegroup_id",
            "summarizeBy": "none"
          },
          {
            "name": "third_party_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f009df4-a3df-4935-bf99-07f815400f5d",
            "sourceColumn": "third_party_id",
            "summarizeBy": "none"
          },
          {
            "name": "third_party_id_string",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44d2fd9f-9d21-4a48-ae37-93f8902de7fd",
            "sourceColumn": "third_party_id_string",
            "summarizeBy": "none"
          },
          {
            "name": "supplier_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29708a9b-5227-43e6-9c37-8e63e25734f3",
            "sourceColumn": "supplier_status",
            "summarizeBy": "none"
          },
          {
            "name": "appointment_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98f1cd34-64d7-4bec-8d2c-e013b075e928",
            "sourceColumn": "appointment_type",
            "summarizeBy": "none"
          },
          {
            "name": "section_timezone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "953e0ccf-ba27-4b45-81e8-fd3075835175",
            "sourceColumn": "section_timezone",
            "summarizeBy": "none"
          },
          {
            "name": "projectinternaltask",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "adee88d3-9912-4fea-9e2b-2fe025dabde0",
            "sourceColumn": "projectinternaltask",
            "summarizeBy": "none"
          },
          {
            "name": "impactlevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60b92a19-ed9f-404a-b545-9df8f2c3f0e6",
            "sourceColumn": "impactlevel",
            "summarizeBy": "none"
          },
          {
            "name": "use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "245778c5-b237-4c74-b05d-6cc664634a91",
            "sourceColumn": "use",
            "summarizeBy": "none"
          },
          {
            "name": "maximumRestrictedPriority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17a4eefb-ac2b-4142-90df-15a615d44fa9",
            "sourceColumn": "maximumRestrictedPriority",
            "summarizeBy": "none"
          },
          {
            "name": "idsummary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0f4e232-046a-410c-bbce-df42cd5f1cd6",
            "sourceColumn": "idsummary",
            "summarizeBy": "none"
          },
          {
            "name": "ticketage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab7b67d1-ae03-4c04-8bd8-47aadbb76fbd",
            "sourceColumn": "ticketage",
            "summarizeBy": "none"
          },
          {
            "name": "useful_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f051565e-44ee-469d-80f2-5ad99539481c",
            "sourceColumn": "useful_count",
            "summarizeBy": "none"
          },
          {
            "name": "notuseful_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b27f63bb-ca04-4d65-93ed-89cd7b33d00e",
            "sourceColumn": "notuseful_count",
            "summarizeBy": "none"
          },
          {
            "name": "itil_requesttype_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e71abeac-2e1e-4aeb-8269-d671f5011dbe",
            "sourceColumn": "itil_requesttype_id",
            "summarizeBy": "none"
          },
          {
            "name": "closed_in_integration_system",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "7342329d-da4f-4d9f-9802-5e26c3ada1c4",
            "sourceColumn": "closed_in_integration_system",
            "summarizeBy": "none"
          },
          {
            "name": "approval_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "827834f4-f7e3-45b3-9437-0a212acfe2b1",
            "sourceColumn": "approval_status",
            "summarizeBy": "none"
          },
          {
            "name": "Date Created",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9dd8f0de-f539-4e2f-84a1-5b1a3cf88913",
            "sourceColumn": "Date Created",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4e544384-e753-41a1-b3df-268e23a11e6f",
        "partitions": [
          {
            "name": "Tickets",
            "mode": "import",
            "queryGroup": "03 Report Tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Tickets Raw\", // end function makeToken",
                "    #\"Changed Types - TF and datetimezones\" = Table.TransformColumnTypes(Source,{{\"dateoccurred\", type datetimezone}, {\"respondbydate\", type datetimezone}, {\"fixbydate\", type datetimezone}, {\"dateassigned\", type datetimezone}, {\"onhold\", type logical}, {\"excludefromsla\", type logical}, {\"lastactiondate\", type datetimezone}, {\"hasbeenclosed\", type logical}, {\"is_vip\", type logical}, {\"isimportantcontact\", type logical}, {\"inactive\", type logical}, {\"release_important\", type logical}, {\"projectinternaltask\", type logical}, {\"closed_in_integration_system\", type logical}}),",
                "    // these hold null or default values",
                "    // response time is currently default date, not actual date - so can't do avg time to respond",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Types - TF and datetimezones\",{\"lastincomingemail\", \"startdate\", \"starttime\", \"starttimeslot\", \"targetdate\", \"targettime\", \"targettimeslot\", \"deadlinedate\", \"respondbydate\", \"fixbydate\", \"category_2\", \"category_3\", \"category_4\"}),",
                "    #\"Replaced blank w/ null\" = Table.ReplaceValue(#\"Removed Columns\",\"\",null,Replacer.ReplaceValue,{\"id\", \"dateoccurred\", \"summary\", \"details\", \"status_id\", \"tickettype_id\", \"sla_id\", \"priority_id\", \"client_id\", \"client_name\", \"site_id\", \"site_name\", \"user_id\", \"user_name\", \"team\", \"agent_id\", \"category_1\", \"estimate\", \"estimatedays\", \"parent_id\", \"child_count\", \"attachment_count\", \"flagged\", \"read\", \"enduserstatus\", \"onhold\", \"dateassigned\", \"excludefromsla\", \"slaholdtime\", \"site_timezone\", \"lastactiondate\", \"organisation_id\", \"department_id\", \"reportedby\", \"user_email\", \"emailtolist\", \"emailtolistsupplier\", \"emailcclist\", \"emailcclistsupplier\", \"matched_kb_id\", \"product_id\", \"release_id\", \"release2_id\", \"release3_id\", \"inventory_number\", \"workflow_id\", \"workflow_step\", \"hasbeenclosed\", \"is_vip\", \"isimportantcontact\", \"inactive\", \"impact\", \"urgency\", \"oppcompanyname\", \"oppvalueadjusted\", \"cost\", \"quantity\", \"projecttimebudget\", \"projectmoneybudget\", \"projecttimeactual\", \"projectmoneyactual\", \"userdef1\", \"userdef2\", \"userdef3\", \"userdef4\", \"userdef5\", \"source\", \"release_important\", \"releasenotegroup_id\", \"third_party_id\", \"third_party_id_string\", \"supplier_status\", \"appointment_type\", \"section_timezone\", \"projectinternaltask\", \"impactlevel\", \"use\", \"maximumRestrictedPriority\", \"idsummary\", \"ticketage\", \"useful_count\", \"notuseful_count\", \"itil_requesttype_id\", \"closed_in_integration_system\", \"approval_status\"}),",
                "    #\"Cleaned Text\" = Table.TransformColumns(#\"Replaced blank w/ null\",{{\"details\", Text.Clean, type text}, {\"summary\", Text.Clean, type text}, {\"client_name\", Text.Clean, type text}, {\"site_name\", Text.Clean, type text}, {\"user_name\", Text.Clean, type text}, {\"team\", Text.Clean, type text}, {\"category_1\", Text.Clean, type text}, {\"reportedby\", Text.Clean, type text}, {\"user_email\", Text.Clean, type text}, {\"emailtolist\", Text.Clean, type text}, {\"emailtolistsupplier\", Text.Clean, type text}, {\"emailcclist\", Text.Clean, type text}, {\"oppcompanyname\", Text.Clean, type text}, {\"userdef1\", Text.Clean, type text}, {\"userdef2\", Text.Clean, type text}, {\"idsummary\", Text.Clean, type text}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(Table.TransformColumnTypes(#\"Cleaned Text\", {{\"emailcclistsupplier\", type text}}, \"en-AU\"),{{\"details\", Text.Trim, type text}, {\"summary\", Text.Trim, type text}, {\"client_name\", Text.Trim, type text}, {\"site_name\", Text.Trim, type text}, {\"user_name\", Text.Trim, type text}, {\"team\", Text.Trim, type text}, {\"category_1\", Text.Trim, type text}, {\"reportedby\", Text.Trim, type text}, {\"user_email\", Text.Trim, type text}, {\"emailtolist\", Text.Trim, type text}, {\"emailtolistsupplier\", Text.Trim, type text}, {\"emailcclist\", Text.Trim, type text}, {\"oppcompanyname\", Text.Trim, type text}, {\"userdef1\", Text.Trim, type text}, {\"userdef2\", Text.Trim, type text}, {\"idsummary\", Text.Trim, type text}}),",
                "    #\"Renamed id to TicketId\" = Table.RenameColumns(#\"Trimmed Text\",{{\"id\", \"ticket id\"}}),",
                "    #\"Added Date occurred\" = Table.AddColumn(#\"Renamed id to TicketId\", \"Date Created\", each DateTime.Date([dateoccurred]), type date)",
                "in",
                "    #\"Added Date occurred\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Agents",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "agent id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd3c5627-4ea8-489d-a25b-4511588a9b4d",
            "sourceColumn": "agent id",
            "summarizeBy": "none"
          },
          {
            "name": "Agent name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9c1e4e7-ceab-42aa-b616-e10dd2664984",
            "sourceColumn": "Agent name",
            "summarizeBy": "none"
          },
          {
            "name": "isdisabled",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "bed2be6b-bf62-4371-ba23-4c31d2d0407e",
            "sourceColumn": "isdisabled",
            "summarizeBy": "none"
          },
          {
            "name": "initials",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adcd47b5-3114-4132-a1c1-cdd9009f99b7",
            "sourceColumn": "initials",
            "summarizeBy": "none"
          },
          {
            "name": "firstname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "240af55c-c38e-4b82-a459-98227ceced44",
            "sourceColumn": "firstname",
            "summarizeBy": "none"
          },
          {
            "name": "surname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6898442-08da-434a-857c-5ded5f649046",
            "sourceColumn": "surname",
            "summarizeBy": "none"
          },
          {
            "name": "jobtitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1444939-8709-4c7e-80a2-f15ec4fdf594",
            "sourceColumn": "jobtitle",
            "summarizeBy": "none"
          },
          {
            "name": "namewithinactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac312ae6-3397-44ba-9b65-c98083214f8c",
            "sourceColumn": "namewithinactive",
            "summarizeBy": "none"
          },
          {
            "name": "can_approve_purchaseorder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "79935ef9-0866-4298-90b4-17ecfd995b00",
            "sourceColumn": "can_approve_purchaseorder",
            "summarizeBy": "none"
          },
          {
            "name": "email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "471478a7-ea53-4233-8a0a-6b9ac416fab7",
            "sourceColumn": "email",
            "summarizeBy": "none"
          },
          {
            "name": "lastlogindate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "57d00ca9-59c6-470d-be7a-ca105a03e649",
            "sourceColumn": "lastlogindate",
            "summarizeBy": "none"
          },
          {
            "name": "linemanager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b8a8e07-c3c3-41f6-8918-fd7eba3dcb2f",
            "sourceColumn": "linemanager",
            "summarizeBy": "none"
          },
          {
            "name": "Primary team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbd9c379-cb70-43db-bf39-f8addfe7bc97",
            "sourceColumn": "Primary team",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "968d6141-c886-4b0d-9eb9-0547f938a6f9",
        "partitions": [
          {
            "name": "Agents",
            "mode": "import",
            "queryGroup": "03 Report Tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Agents Raw\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"agent id\", \"name\", \"Primary team\", \"isdisabled\", \"initials\", \"firstname\", \"surname\", \"jobtitle\", \"linemanager\", \"namewithinactive\", \"can_approve_purchaseorder\", \"email\", \"lastlogindate\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"name\", \"Agent name\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Agent teams",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "agent id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e9ad7052-bdf3-4218-b144-893e22fea904",
            "sourceColumn": "agent id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5fab22b3-44ea-4b4e-8988-6a11e172e2d8",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "team_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bab18e4e-a2af-44ed-87dc-4207ad335623",
            "sourceColumn": "team_id",
            "summarizeBy": "none"
          }
        ],
        "description": "Many : 1 table, what teams does each agent belong to",
        "isHidden": true,
        "lineageTag": "e690a564-122c-4406-b802-ac2061a749a4",
        "partitions": [
          {
            "name": "Agent teams",
            "mode": "import",
            "queryGroup": "03 Report Tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Agents Raw\",",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"agent id\", \"name\", \"teams\"}),",
                "    #\"Expanded teams\" = Table.ExpandListColumn(#\"Removed Other Columns\", \"teams\"),",
                "    #\"Expanded teams1\" = Table.ExpandRecordColumn(#\"Expanded teams\", \"teams\", {\"team_id\"}, {\"team_id\"})",
                "in",
                "    #\"Expanded teams1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Teams",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "team_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1e9324c-54a7-44ec-80fa-d9ad3bc78822",
            "sourceColumn": "team_id",
            "summarizeBy": "none"
          },
          {
            "name": "guid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07c942a0-0ec2-4643-ab79-4fce0f3bcea2",
            "sourceColumn": "guid",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05b82b60-4965-4052-b9d3-c77a1cc87dfa",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "department_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb5a68c5-972f-4beb-a748-fbb56dfc4377",
            "sourceColumn": "department_id",
            "summarizeBy": "none"
          },
          {
            "name": "department_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e2a0526-d358-45fd-8a89-32481b645e87",
            "sourceColumn": "department_name",
            "summarizeBy": "none"
          },
          {
            "name": "inactive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "b5372a7d-03a6-4d72-a647-38d44d17f12e",
            "sourceColumn": "inactive",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4f145061-06a6-4a21-935b-ecdc6a7b0f0d",
        "partitions": [
          {
            "name": "Teams",
            "mode": "import",
            "queryGroup": "01 API returns\\01-00 SingleQuery",
            "source": {
              "expression": [
                "let",
                "    // a function which generates the token - needs to happen at the same time as the query, so PBI doesn't do dumb firewall stuff",
                "    makeToken = (#\"HaloITSM-Resource\" as any, #\"HaloITSM-ClientID\" as any, #\"HaloITSM-Secret\" as any) => let",
                "        loginURL = #\"HaloITSM-AuthURL\",",
                "        TokenUri = \"/token\", // which domain is this a token for",
                "        ResourceId = #\"HaloITSM-Resource\", // where is this token for",
                "        TokenResponse = Json.Document(",
                "            Web.Contents(loginURL",
                "\t\t\t    , [RelativePath = TokenUri",
                "\t\t\t    , Content = Text.ToBinary(Uri.BuildQueryString([grant_type = \"client_credentials\", client_id = #\"HaloITSM-ClientID\", client_secret = #\"HaloITSM-Secret\", scope = \"all\"]))",
                "\t\t\t\t, Headers = [#\"Content-Type\" = \"application/x-www-form-urlencoded\"], ManualStatusHandling = {400}",
                "\t\t\t    ]",
                "            ) // end web contents",
                "        ), // end json",
                "        generatedToken = TokenResponse[access_token] // assign token value",
                "    in",
                "    generatedToken,",
                "    myToken = makeToken(",
                "                        #\"HaloITSM-ResourceURL\"",
                "                        , #\"HaloITSM-ClientID\"",
                "                        , #\"HaloITSM-Secret\"",
                "                    ) // end makeToken",
                "    , ",
                "    // Ping API for json",
                "    Source = Json.Document(",
                "        Web.Contents(",
                "            #\"HaloITSM-ResourceURL\"",
                "            , [",
                "                RelativePath = \"Team\"",
                "                , Headers = [",
                "                    Authorization = \"Bearer \" ",
                "                    &  myToken",
                "                ]",
                "            ]",
                "        )",
                "    ),",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"guid\", \"name\", \"sequence\", \"forrequests\", \"foropps\", \"forprojects\", \"ticket_count\", \"department_id\", \"department_name\", \"inactive\"}, {\"team_id\", \"guid\", \"name\", \"sequence\", \"forrequests\", \"foropps\", \"forprojects\", \"ticket_count\", \"department_id\", \"department_name\", \"inactive\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Column1\",{{\"forprojects\", type logical}, {\"foropps\", type logical}, {\"forrequests\", type logical}, {\"inactive\", type logical}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"team_id\", \"guid\", \"name\", \"department_id\", \"department_name\", \"inactive\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Statuses",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "status id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ebf399d1-a023-40ac-af95-633509ca4a73",
            "sourceColumn": "status id",
            "summarizeBy": "none"
          },
          {
            "name": "guid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5ea2a93-8ba0-453f-bb1d-fbae7ce15370",
            "sourceColumn": "guid",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "82486b6d-1e75-4528-a9f8-4df6b0ac534c",
            "sortByColumn": "Order",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "afaa319a-fa20-4469-b61f-3937b26c247c",
            "sortByColumn": "Order",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "External",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c0f53131-b460-4b95-9768-019e287dfd9e",
            "sourceColumn": "External",
            "summarizeBy": "none"
          },
          {
            "name": "Terminal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "fb6cad55-eb9e-4015-a9f2-326e1b498084",
            "sourceColumn": "Terminal",
            "summarizeBy": "none"
          },
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4d7e1d23-62c9-41c9-b020-274ea4da12bc",
            "sourceColumn": "Order",
            "summarizeBy": "none"
          }
        ],
        "description": "labelled and enhanced ticket statuses",
        "lineageTag": "4a24ed7e-04df-406f-989d-9fe97d1156a8",
        "partitions": [
          {
            "name": "Statuses",
            "mode": "import",
            "queryGroup": "03 Report Tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Statuses Raw\",",
                "    // merged with manual mapping table, to apply higher level categories not present in Halo",
                "    #\"Merged w/ StatusMapping\" = Table.NestedJoin(Source, {\"status id\"}, StatusMapping, {\"status id\"}, \"StatusMapping\", JoinKind.LeftOuter),",
                "    #\"Expanded StatusMapping\" = Table.ExpandTableColumn(#\"Merged w/ StatusMapping\", \"StatusMapping\", {\"Category\", \"External\", \"Order\", \"Terminal\"}, {\"Category\", \"External\", \"Order\", \"Terminal\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded StatusMapping\",{{\"status id\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MeasuresTable",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "46afd73f-4f41-4c4e-8139-6b1b8a1dcd80",
        "measures": [
          {
            "name": "Tickets",
            "displayFolder": "Tickets",
            "expression": [
              "CALCULATE(",
              "    DISTINCTCOUNT(Tickets[ticket id])",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "47c7f8f1-2e89-47b7-aff5-491daccb5d98"
          },
          {
            "name": "Last Refreshed",
            "displayFolder": "Utilities",
            "expression": "FORMAT(NOW(), \"yyyy/mm/dd HH:mm\")",
            "lineageTag": "60b49eef-46e4-417d-b1d1-892b698d8c17"
          },
          {
            "name": "Blocked Tickets",
            "displayFolder": "Tickets\\Subcategories",
            "expression": [
              "CALCULATE(",
              "    [Tickets]",
              "    , 'Statuses'[Category] = \"Oh Hold\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "f41c5a2e-c4e8-4612-be6b-ffeddf5e249d"
          },
          {
            "name": "Cancelled Tickets",
            "displayFolder": "Tickets\\Subcategories",
            "expression": [
              "CALCULATE(",
              "    [Tickets]",
              "    , 'Statuses'[Category] = \"Cancelled\"",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "61613189-e81c-4187-a4f4-fe1ac1b42d81"
          },
          {
            "name": "Waiting Tickets",
            "displayFolder": "Tickets\\Subcategories",
            "expression": [
              "CALCULATE(",
              "    [Tickets]",
              "    , (",
              "        'Statuses'[Category] = \"Waiting\" ",
              "        || 'Statuses'[Category] = \"Awaiting Business\"",
              "        || 'Statuses'[Category] = \"Notified\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "6b7935ac-86c0-4e84-bea2-127a27a1521a"
          },
          {
            "name": "WIP Tickets",
            "displayFolder": "Tickets\\Subcategories",
            "expression": [
              "CALCULATE(",
              "    [Tickets]",
              "    , 'Statuses'[Category] = \"WIP\"",
              ") // end calculate"
            ],
            "formatString": "0",
            "lineageTag": "119d180c-7fa7-4e0e-9344-378de9154dab"
          },
          {
            "name": "Resolved Tickets",
            "displayFolder": "Tickets\\Subcategories",
            "expression": [
              "CALCULATE(",
              "    [Tickets]",
              "    , 'Statuses'[Category] = \"Done\" || 'Statuses'[Category] = \"Cloned\"",
              ") // end calc"
            ],
            "formatString": "#,0",
            "lineageTag": "73f7adb3-fd1c-4889-b907-355ce06bbe7f"
          },
          {
            "name": "External Tickets",
            "displayFolder": "Tickets\\Subcategories",
            "expression": [
              "CALCULATE(",
              "    [Tickets]",
              "    , 'Statuses'[External] = TRUE",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "cd6a1dd0-97a3-4508-b5e9-6fb603f9fbd5"
          },
          {
            "name": "Pending Tickets",
            "displayFolder": "Tickets\\Subcategories",
            "expression": [
              "CALCULATE(",
              "    [Tickets]",
              "    , (",
              "        'Statuses'[Category] = \"TO DO\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "21b8b513-3a6b-459b-bd80-207dd4f8e09f"
          },
          {
            "name": "Resolution rate",
            "expression": "[Resolved Tickets] / [Tickets]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "be83b48e-5207-4e91-819b-55b4181dec90"
          }
        ],
        "partitions": [
          {
            "name": "MeasuresTable",
            "mode": "import",
            "queryGroup": "00 Utilities",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateDimensionBI",
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e45604b3-ff90-4d48-8736-03bded736b35",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9a4f62bc-15ef-44f3-9175-e7c789239775",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3839dfff-93a0-4c2b-9499-a54fb0e3a5d0",
            "sourceColumn": "Start of Year",
            "summarizeBy": "none"
          },
          {
            "name": "End of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5b24a611-dfd6-4688-a5b2-0105400cce33",
            "sourceColumn": "End of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2dc7f129-2d29-4da8-87ba-583af8e77301",
            "sourceColumn": "Month Number",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70c5742a-5b90-4a21-9469-77ebe6619ae8",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f8cc54f9-839b-402f-a8fd-41a794e36cba",
            "sourceColumn": "Month Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Month End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8c721c52-f9d0-4ac4-82a1-15827e2ab834",
            "sourceColumn": "Month End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Days in Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "add5890b-0cf7-4ea7-967a-15e9fe1cabf6",
            "sourceColumn": "Days in Month",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f4aba805-c177-4259-9896-3c751b6a6b2a",
            "sourceColumn": "Quarter Number",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "83c21a8d-0b04-4e28-8404-14ceae8268df",
            "sourceColumn": "Quarter Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a843dc5b-0058-48b1-8cd4-76e4e53ec32c",
            "sourceColumn": "Quarter End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Week Number of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2318b807-03ea-499a-b5a6-edd6c6efbe8e",
            "sourceColumn": "Week Number of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Week Number of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80bb4c70-7e48-4650-8b93-e4343e95d028",
            "sourceColumn": "Week Number of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Week Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "973f817e-c814-4471-9ef5-ba6bc68cd0a6",
            "sourceColumn": "Week Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "Week End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "323144b6-c08e-4d02-b997-333c94ce3aaf",
            "sourceColumn": "Week End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f989ca1e-4aa1-4236-8af8-38681b31bd1f",
            "sourceColumn": "Day of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b18a20f-12c2-4717-89b2-91a20f69177d",
            "sourceColumn": "Day of Week",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "14758635-3bda-41b0-b449-7ea0d1cd67e8",
            "sourceColumn": "Day of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b60baca5-dd8f-449b-abe2-cba7618e1b4a",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "t-90",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "eeaedb3b-3539-445c-8d55-78a10a9a4c4e",
            "sourceColumn": "t-90",
            "summarizeBy": "none"
          },
          {
            "name": "isFuture",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "009dc3e4-d396-4b2e-99b1-9768a744ec44",
            "sourceColumn": "isFuture",
            "summarizeBy": "none"
          },
          {
            "name": "Reporting Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "a31d2b1f-8416-4e71-9aa0-160897cff5a7",
            "sourceColumn": "Reporting Month",
            "summarizeBy": "none"
          },
          {
            "name": "Reporting Month - Last year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "ffe57c43-9b9d-4476-bda4-d28ff1698d6d",
            "sourceColumn": "Reporting Month - Last year",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "07bdeb20-11ef-4d1e-9197-64b3dcc87b6b",
        "partitions": [
          {
            "name": "DateDimensionBI",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PowerPlatform.Dataflows(null),",
                "    Workspaces = Source{[Id=\"Workspaces\"]}[Data],",
                "    #\"6f7c04d6-f8ec-4722-a220-364c2598401d\" = Workspaces{[workspaceId=\"6f7c04d6-f8ec-4722-a220-364c2598401d\"]}[Data],",
                "    #\"b9ac9667-3d19-4d70-8128-20287e809db0\" = #\"6f7c04d6-f8ec-4722-a220-364c2598401d\"{[dataflowId=\"b9ac9667-3d19-4d70-8128-20287e809db0\"]}[Data],",
                "    DateDimensionBI_ = #\"b9ac9667-3d19-4d70-8128-20287e809db0\"{[entity=\"DateDimensionBI\",version=\"\"]}[Data]",
                "in",
                "    DateDimensionBI_"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}